/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/system/introspection/libdispatch.dylib
 */

@interface OS_dispatch_data_empty : OS_dispatch_data

+ (id)allocWithZone:(struct _NSZone { }*)arg1;
+ (void)load;

- (void*)_getContext;
- (void)_setContext:(void*)arg1;
- (void)_setFinalizer:(int (*)arg1;
- (void)_setTargetQueue:(id)arg1;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (unsigned int)retainCount;

@end
