/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
 */

@interface FBSSceneSettingsDiffInspector : FBSSettingsDiffInspector

// FBSSceneSettingsDiffInspector (null)

- (void)observeClassWithBlock:(id /* block */)arg1;
- (void)observeFrameWithBlock:(id /* block */)arg1;
- (void)observeInterfaceOrientationWithBlock:(id /* block */)arg1;
- (void)observeIsBackgroundedWithBlock:(id /* block */)arg1;
- (void)observeLevelWithBlock:(id /* block */)arg1;
- (void)observeOcclusionsWithBlock:(id /* block */)arg1;

@end
