/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
 */

@interface FBSSceneClientSettingsDiff : FBSSettingsDiff

// FBSSceneClientSettingsDiff (null)

+ (id)diffFromSettings:(id)arg1 toSettings:(id)arg2;

- (BOOL)inspectPreferredInterfaceOrientation:(int*)arg1;
- (BOOL)inspectPreferredLevel:(float*)arg1;
- (BOOL)inspectPreferredSceneHostIdentifier:(id*)arg1;
- (id)keyDescriptionForSetting:(unsigned int)arg1;
- (id)settingsByApplyingToMutableCopyOfSettings:(id)arg1;
- (id)valueDescriptionForFlag:(int)arg1 object:(id)arg2 ofSetting:(unsigned int)arg3;

@end
