/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
 */

@interface FBSSystemServiceUtility : NSObject

// FBSSystemServiceUtility (null)

+ (id)auditTokenFromClientPort:(unsigned int)arg1;
+ (void)cleanupClientPort:(unsigned int)arg1;
+ (unsigned int)createClientPort;

@end
