/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
 */

@interface FBSUIApplicationSystemService : NSObject {
    <FBSUIApplicationSystemServiceDelegate> * _delegate;
    NSObject<OS_dispatch_queue> * _delegateQueue;
}

@property (nonatomic, readonly) double backgroundTimeRemaining;
@property (nonatomic) int badgeNumber;
@property (nonatomic, copy) NSString *badgeString;
@property (nonatomic) float currentBacklightLevel;
@property (nonatomic) <FBSUIApplicationSystemServiceDelegate> *delegate;

// FBSUIApplicationSystemService (null)

- (id)_getBadgeValue;
- (int)activeInterfaceOrientation;
- (double)backgroundTimeRemaining;
- (int)badgeNumber;
- (id)badgeString;
- (float)currentBacklightLevel;
- (void)dealloc;
- (id)delegate;
- (id)init;
- (id)initWithQueue:(id)arg1;
- (void)setBadgeNumber:(int)arg1;
- (void)setBadgeString:(id)arg1;
- (void)setCurrentBacklightLevel:(float)arg1;
- (void)setDelegate:(id)arg1;
- (BOOL)setNextWakeInterval:(double)arg1;
- (void)suspendCurrentApplication;

@end
