/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
 */

@interface FBSUIApplicationWorkspaceClient : FBSWorkspaceClient

@property (nonatomic, readonly) <FBSUIApplicationWorkspaceClientDelegate> *delegate;

// FBSUIApplicationWorkspaceClient (null)

- (void)_queue_handleAssertionExpirationImminent:(id)arg1;
- (void)_queue_handleExit:(id)arg1;
- (void)_queue_handleLaunch:(id)arg1;
- (BOOL)_queue_handleMessageWithType:(int)arg1 message:(id)arg2;
- (BOOL)willObserveLayersManually;

@end
