/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
 */

@interface FBSWorkspaceSceneEvent : FBSWorkspaceEvent {
    NSString * _sceneID;
}

@property (nonatomic, copy) NSString *sceneID;

// FBSWorkspaceSceneEvent (null)

- (void)dealloc;
- (void)encodeWithXPCDictionary:(id)arg1;
- (id)initWithXPCDictionary:(id)arg1;
- (id)sceneID;
- (void)setSceneID:(id)arg1;

@end
