/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
 */

@interface FBSWorkspaceCreateSceneRequestEvent : FBSWorkspaceEvent {
    FBSSceneClientSettingsDiff * _clientSettings;
    NSString * _identifier;
}

@property (nonatomic, retain) FBSSceneClientSettingsDiff *clientSettingsDiff;
@property (nonatomic, retain) NSString *identifier;

// FBSWorkspaceCreateSceneRequestEvent (null)

- (id)clientSettingsDiff;
- (void)dealloc;
- (void)encodeWithXPCDictionary:(id)arg1;
- (id)identifier;
- (id)initWithXPCDictionary:(id)arg1;
- (void)setClientSettingsDiff:(id)arg1;
- (void)setIdentifier:(id)arg1;

@end
