/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libLinearAlgebra.dylib
 */

@interface OS_la_object : OS_object <OS_la_object>

// OS_la_object (null)

- (void)_dispose;
- (id)debugDescription;
- (id)description;
- (id)init;

@end
