/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface _NSProgressFractionTuple : NSObject {
    _NSProgressFraction * _next;
    _NSProgressFraction * _previous;
}

@property (copy) _NSProgressFraction *next;
@property (copy) _NSProgressFraction *previous;

- (void)dealloc;
- (id)next;
- (id)previous;
- (BOOL)previousIsEqualToNext;
- (void)setNext:(id)arg1;
- (void)setPrevious:(id)arg1;

@end
