/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface _NSPredicateOperatorUtilities : NSObject

+ (long)copyRegexFindSafePattern:(id)arg1 toBuffer:(unsigned short*)arg2;
+ (BOOL)doRegexForString:(id)arg1 pattern:(id)arg2 likeProtect:(BOOL)arg3 flags:(unsigned int)arg4 context:(struct { id x1; void x2; }*)arg5;
+ (id)newStringFrom:(id)arg1 usingUnicodeTransforms:(unsigned int)arg2;
+ (struct __CFLocale { }*)retainedLocale;

@end
