/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface _NSUndoBlockInvocation : _NSUndoObject {
    id /* block */  _handler;
}

- (void)dealloc;
- (void)finalize;
- (id)initWithTarget:(id)arg1 handler:(id /* block */)arg2;
- (void)invoke;

@end
