/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface _NSUndoBeginMark : _NSUndoObject {
    id  _groupIdentifier;
    BOOL  _isDiscardable;
}

- (void)dealloc;
- (id)description;
- (id)groupIdentifier;
- (BOOL)isBeginMark;
- (BOOL)isDiscardable;
- (void)setDiscardable:(BOOL)arg1;
- (void)setGroupIdentifier:(id)arg1;

@end
