/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface _NSXPCBoost : NSObject {
    NSObject<OS_xpc_object> * _event;
}

- (id)_initWithEvent:(id)arg1;
- (void)dealloc;

@end
