/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface _NSXPCDistantObjectWithError : _NSXPCDistantObject {
    id /* block */  _errorBlock;
}

@property (copy) id /* block */ errorBlock;

- (id)_initWithConnection:(id)arg1 proxyNumber:(unsigned long long)arg2 generationCount:(unsigned long long)arg3 interface:(id)arg4 error:(id /* block */)arg5;
- (void)dealloc;
- (id /* block */)errorBlock;
- (void)forwardInvocation:(id)arg1;
- (void)setErrorBlock:(id /* block */)arg1;

@end
