/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface _NSXPCConnectionImportInfo : NSObject {
    unsigned long long  _generationCount;
    struct __CFSet { } * _knownProxies;
    NSLock * _lock;
    struct __CFDictionary { } * _proxyNumberToCount;
}

- (void)addProxy:(id)arg1;
- (void)dealloc;
- (void)finalize;
- (id)init;
- (BOOL)removeProxy:(id)arg1;

@end
