/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSConcreteDistantObjectRequest : NSDistantObjectRequest {
    NSConnection * connection;
    id  conversation;
    NSArray * importedObjects;
    NSInvocation * invocation;
    unsigned int  sequence;
}

- (id)connection;
- (id)conversation;
- (void)dealloc;
- (id)initWithInvocation:(id)arg1 conversation:(id)arg2 sequence:(unsigned int)arg3 importedObjects:(id)arg4 connection:(id)arg5;
- (id)invocation;
- (void)replyWithException:(id)arg1;

@end
