/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSConcreteMapTableValueEnumerator : NSEnumerator {
    unsigned int  counter;
    NSConcreteMapTable * mapTable;
}

+ (id)enumeratorWithMapTable:(id)arg1;

- (void)dealloc;
- (id)nextObject;

@end
