/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSCompoundPredicate : NSPredicate {
    void * _reserved2;
    NSArray * _subpredicates;
    unsigned int  _type;
}

@property (readonly) unsigned int compoundPredicateType;
@property (readonly, copy) NSArray *subpredicates;

+ (id)_operatorForType:(unsigned int)arg1;
+ (id)andPredicateWithSubpredicates:(id)arg1;
+ (id)notPredicateWithSubpredicate:(id)arg1;
+ (id)orPredicateWithSubpredicates:(id)arg1;
+ (BOOL)supportsSecureCoding;

- (void)_acceptSubpredicates:(id)arg1 flags:(unsigned int)arg2;
- (id)_predicateOperator;
- (id)_subpredicateDescription:(id)arg1;
- (void)acceptVisitor:(id)arg1 flags:(unsigned int)arg2;
- (void)allowEvaluation;
- (unsigned int)compoundPredicateType;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (BOOL)evaluateWithObject:(id)arg1 substitutionVariables:(id)arg2;
- (unsigned int)hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithType:(unsigned int)arg1 subpredicates:(id)arg2;
- (BOOL)isEqual:(id)arg1;
- (id)predicateFormat;
- (id)predicateOperator;
- (id)predicateWithSubstitutionVariables:(id)arg1;
- (id)subpredicates;

// NSCompoundPredicate (NSMetadataQueryPrivate)

- (id)generateMetadataDescription;

@end
