/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSConcreteFileHandleARCWeakRef : NSObject {
    id  ref;
}

- (void)dealloc;
- (id)loadWeak;
- (void)storeWeak:(id)arg1;

@end
