/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSConcreteProtocolChecker : NSProtocolChecker {
    Protocol * _protocol;
    NSObject * _target;
}

- (void)dealloc;
- (id)initWithTarget:(id)arg1 protocol:(id)arg2;
- (id)protocol;
- (id)target;

@end
