/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSConnectionHelper : NSObject {
    NSConnection * parent;
    BOOL  remoteUsesKeyedDO;
    double  repLim;
    double  reqLim;
    BOOL  useKeyedDO;
    NSSet * whitelist;
}

- (void)dealloc;
- (void)finalize;
- (id)init;
- (void)setWhitelist:(id)arg1;

@end
