/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSConcreteValue : NSValue {
    unsigned int  _specialFlags;
    void * typeInfo;
}

+ (void)initialize;
+ (BOOL)supportsSecureCoding;

- (BOOL)_matchType:(const char *)arg1 size:(unsigned int)arg2;
- (const void*)_value;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (void)getValue:(void*)arg1;
- (unsigned int)hash;
- (BOOL)isEqualToValue:(id)arg1;
- (const char *)objCType;

@end
