/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSConcreteSetChange : NSSetChange {
    unsigned int  _changeType;
    id  _value;
}

- (unsigned int)changeType;
- (void)dealloc;
- (id)initWithType:(unsigned int)arg1 object:(id)arg2;
- (id)value;

@end
