/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSDOStreamData : NSMutableData {
    id  refObject;
    /* Warning: unhandled struct encoding: '{?="data"@"datap"*"limitp"*"startp"*"callback"@"datapVM"c}' */ struct { 
        id data; 
    }  stream;
}

- (const void*)bytes;
- (void)dealloc;
- (void)finalize;
- (id)init;
- (unsigned int)length;
- (void*)mutableBytes;

@end
