/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSFilterObservationTransformer : NSObservationTransformer {
    id  _predicate;
}

+ (id)filterWithBlock:(id /* block */)arg1;

- (void)_receiveBox:(id)arg1;
- (void)dealloc;
- (id)initWithBlock:(id /* block */)arg1;

@end
