/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSFilePromiseWriteToken : NSObject {
    NSURL * logicalURL;
    NSURL * promiseURL;
}

@property (copy) NSURL *logicalURL;
@property (copy) NSURL *promiseURL;

- (void)dealloc;
- (id)logicalURL;
- (id)promiseURL;
- (void)setLogicalURL:(id)arg1;
- (void)setPromiseURL:(id)arg1;

@end
