/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSKeyValueSet : NSSet <NSKeyValueProxyCaching> {
    NSObject * _container;
    NSString * _key;
    NSKeyValueNonmutatingSetMethodSet * _methods;
}

+ (struct { unsigned int x1; /* Warning: unhandled array encoding: '[4@]}' */ id x2[4]; void*x3; void*x4; void*x5; void*x6; void*x7; void*x8; void*x9; void*x10; void*x11; void*x12; void*x13; void*x14; void*x15; void*x16; void*x17; out void*x18; void*x19; void*x20; void*x21; void*x22; void*x23; inout unsigned short x24; void*x25; void*x26; void*x27; void*x28; in double x29; void*x30; double x31; void*x32; void*x33; void*x34; void*x35; long x36; void*x37; const void*x38; void*x39; void*x40; const void*x41; short x42; short x43; int x44; out in unsigned char x45; void*x46; void*x47; BOOL x48; void*x49; int x50; in void*x51; void*x52; void*x53; short x54; void*x55; long x56; void*x57; void*x58; void*x59; void*x60; void*x61; void*x62; void*x63; void*x64; void*x65; void*x66; void*x67; void*x68; void*x69; void*x70; void*x71; void*x72; void*x73; void*x74; void*x75; void*x76; void*x77; void*x78; void*x79; id x80; void*x81; }*)_proxyNonGCPoolPointer;
+ (id)_proxyShare;

- (id)_proxyInitWithContainer:(id)arg1 getter:(id)arg2;
- (struct { id x1; })_proxyLocator;
- (void)_proxyNonGCFinalize;
- (unsigned int)count;
- (void)dealloc;
- (id)member:(id)arg1;
- (id)objectEnumerator;

@end
