/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSKeyPathExpression : NSFunctionExpression

- (void)dealloc;
- (id)initWithKeyPath:(id)arg1;
- (id)initWithOperand:(id)arg1 andKeyPath:(id)arg2;
- (id)keyPath;
- (id)pathExpression;
- (id)predicateFormat;

@end
