/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSKeyValueArray : NSArray <NSKeyValueProxyCaching> {
    NSObject * _container;
    NSString * _key;
    NSKeyValueNonmutatingArrayMethodSet * _methods;
}

+ (struct { unsigned int x1; /* Warning: unhandled array encoding: '[4@]}' */ id x2[4]; void*x3; void*x4; void*x5; void*x6; void*x7; void*x8; void*x9; void*x10; void*x11; void*x12; void*x13; void*x14; void*x15; void*x16; void*x17; out void*x18; void*x19; void*x20; void*x21; void*x22; void*x23; void*x24; void*x25; unsigned int x26; void*x27; out BOOL x28; void*x29; short x30; void*x31; in void*x32; int x33; in void*x34; void*x35; void*x36; in void*x37; void*x38; short x39; void*x40; void*x41; const void*x42; void*x43; void*x44; BOOL x45; out void*x46; in int x47; void*x48; void*x49; const void*x50; void*x51; void*x52; void*x53; void*x54; void*x55; void*x56; void*x57; void*x58; void*x59; void*x60; void*x61; void*x62; void*x63; char *x64; void*x65; }*)_proxyNonGCPoolPointer;
+ (id)_proxyShare;

- (id)_proxyInitWithContainer:(id)arg1 getter:(id)arg2;
- (struct { id x1; })_proxyLocator;
- (void)_proxyNonGCFinalize;
- (unsigned int)count;
- (void)dealloc;
- (void)getObjects:(id*)arg1 range:(struct _NSRange { unsigned int x1; unsigned int x2; })arg2;
- (id)objectAtIndex:(unsigned int)arg1;
- (id)objectsAtIndexes:(id)arg1;

@end
