/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSKeyValueObservationInfo : NSObject {
    unsigned int  _cachedHash;
    BOOL  _cachedIsShareable;
    NSArray * _observances;
    int  _retainCountMinusOne;
}

- (id)_initWithObservances:(id*)arg1 count:(unsigned int)arg2;
- (BOOL)_isDeallocating;
- (BOOL)_tryRetain;
- (void)dealloc;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (oneway void)release;
- (id)retain;
- (unsigned int)retainCount;

@end
