/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSScanner : NSObject <NSCopying>

@property BOOL caseSensitive;
@property (copy) NSCharacterSet *charactersToBeSkipped;
@property (retain) id locale;
@property unsigned int scanLocation;
@property (readonly, copy) NSString *string;

+ (id)allocWithZone:(struct _NSZone { }*)arg1;
+ (id)localizedScannerWithString:(id)arg1;
+ (id)scannerWithString:(id)arg1;

- (id)_invertedSkipSet;
- (BOOL)caseSensitive;
- (id)charactersToBeSkipped;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)initWithString:(id)arg1;
- (BOOL)isAtEnd;
- (id)locale;
- (BOOL)scanCharactersFromSet:(id)arg1 intoString:(id*)arg2;
- (BOOL)scanDouble:(double*)arg1;
- (BOOL)scanFloat:(float*)arg1;
- (BOOL)scanHexDouble:(double*)arg1;
- (BOOL)scanHexFloat:(float*)arg1;
- (BOOL)scanHexInt:(unsigned int*)arg1;
- (BOOL)scanHexLongLong:(unsigned long long*)arg1;
- (BOOL)scanInt:(int*)arg1;
- (BOOL)scanInteger:(int*)arg1;
- (unsigned int)scanLocation;
- (BOOL)scanLongLong:(long long*)arg1;
- (BOOL)scanString:(id)arg1 intoString:(id*)arg2;
- (BOOL)scanUnsignedInteger:(unsigned int*)arg1;
- (BOOL)scanUnsignedLongLong:(unsigned long long*)arg1;
- (BOOL)scanUpToCharactersFromSet:(id)arg1 intoString:(id*)arg2;
- (BOOL)scanUpToString:(id)arg1 intoString:(id*)arg2;
- (void)setCaseSensitive:(BOOL)arg1;
- (void)setCharactersToBeSkipped:(id)arg1;
- (void)setLocale:(id)arg1;
- (void)setScanLocation:(unsigned int)arg1;
- (id)string;

// NSScanner (NSDecimalNumberScanning)

- (BOOL)scanDecimal:(struct { unsigned int x1 : 8; unsigned int x2 : 4; unsigned int x3 : 1; unsigned int x4 : 1; unsigned int x5 : 18; unsigned short x6[8]; }*)arg1;

// NSScanner (NSRemainingString)

- (id)_remainingString;
- (BOOL)_scanDecimal:(unsigned int)arg1 into:(int*)arg2;

@end
