/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSSetChange : NSObject

@property (readonly) unsigned int changeType;
@property (readonly) id value;

+ (id)allocWithZone:(struct _NSZone { }*)arg1;

- (unsigned int)changeType;
- (id)initWithType:(unsigned int)arg1 object:(id)arg2;
- (id)value;

@end
