/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSSearchPathEnumerator : NSEnumerator {
    unsigned int  directory;
    unsigned int  domainMask;
    long  state;
}

- (id)initWithDirectory:(unsigned int)arg1 domains:(unsigned int)arg2;
- (id)nextObject;

@end
