/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation
 */

@interface NSUnkeyedPortCoder : NSConcretePortCoder {
    unsigned int  componentIndex;
    NSMutableArray * components;
    NSDOStreamData * doStreamData;
    NSMutableArray * importedObjects;
    BOOL  isBycopy;
    BOOL  isByref;
    BOOL  isValid;
    id  rcvPort;
    id  sndPort;
}

+ (void)_enableLogging:(BOOL)arg1;
+ (id)allocWithZone:(struct _NSZone { }*)arg1;

- (id)_proxyForLocalObject:(id)arg1;
- (id)components;
- (id)connection;
- (void)dealloc;
- (id)debugDescription;
- (void*)decodeBytesWithReturnedLength:(unsigned int*)arg1;
- (id)decodeDataObject;
- (id)decodeInvocation;
- (id)decodePortObject;
- (id)decodeRetainedObject;
- (void)decodeReturnValue:(id)arg1;
- (void)decodeValueOfObjCType:(const char *)arg1 at:(void*)arg2;
- (void)dispatch;
- (void)encodeBycopyObject:(id)arg1;
- (void)encodeByrefObject:(id)arg1;
- (void)encodeBytes:(const void*)arg1 length:(unsigned int)arg2;
- (void)encodeDataObject:(id)arg1;
- (void)encodeInvocation:(id)arg1;
- (void)encodeObject:(id)arg1 isBycopy:(BOOL)arg2 isByref:(BOOL)arg3;
- (void)encodePortObject:(id)arg1;
- (void)encodeReturnValue:(id)arg1;
- (void)encodeValueOfObjCType:(const char *)arg1 at:(const void*)arg2;
- (id)finishedComponents;
- (void)importObject:(id)arg1;
- (id)importedObjects;
- (id)initWithReceivePort:(id)arg1 sendPort:(id)arg2 components:(id)arg3;
- (void)invalidate;
- (BOOL)isBycopy;
- (BOOL)isByref;
- (int)versionForClassName:(id)arg1;

@end
