/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/UserNotificationServices.framework/UserNotificationServices
 */

@interface UNSLocalNotification : NSObject

// UNSLocalNotification (null)

+ (void)_scheduleLocalNotifications:(id)arg1 cancel:(BOOL)arg2 replace:(BOOL)arg3 snooze:(BOOL)arg4 optionalBundleIdentifier:(id)arg5;
+ (void)_scheduleLocalNotifications:(id)arg1 cancel:(BOOL)arg2 replace:(BOOL)arg3 snooze:(BOOL)arg4 optionalBundleIdentifier:(id)arg5 waitUntilDone:(BOOL)arg6;
+ (void)cancelAllLocalNotifications;
+ (void)cancelAllLocalNotificationsForBundleIdentifier:(id)arg1;
+ (void)cancelLocalNotification:(id)arg1;
+ (void)cancelLocalNotification:(id)arg1 bundleIdentifier:(id)arg2;
+ (void)cancelLocalNotification:(id)arg1 bundleIdentifier:(id)arg2 waitUntilDone:(BOOL)arg3;
+ (unsigned int)currentAllowedNotificationTypesForBundleID:(id)arg1;
+ (id)currentUserNotificationSettings;
+ (id)currentUserNotificationSettingsForBundleID:(id)arg1;
+ (void)migrateUserNotificationSettingsForBundleIdentifierPushSettingsPairs:(id)arg1;
+ (void)registerBadgePermissionForBundleIdentifier:(id)arg1;
+ (void)registerUserNotificationSettings:(id)arg1;
+ (void)registerUserNotificationSettings:(id)arg1 bundleIdentifier:(id)arg2;
+ (void)scheduleLocalNotification:(id)arg1;
+ (void)scheduleLocalNotification:(id)arg1 bundleIdentifier:(id)arg2;
+ (void)scheduleLocalNotification:(id)arg1 bundleIdentifier:(id)arg2 waitUntilDone:(BOOL)arg3;
+ (id)scheduledLocalNotifications;
+ (id)scheduledLocalNotificationsForBundleIdentifier:(id)arg1;
+ (void)setScheduledLocalNotifications:(id)arg1;
+ (void)setScheduledLocalNotifications:(id)arg1 bundleIdentifier:(id)arg2;
+ (void)snoozeLocalNotification:(id)arg1 bundleIdentifier:(id)arg2;

@end
