/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/UserNotificationServices.framework/UserNotificationServices
 */

@interface UNSRemoteNotification : NSObject

// UNSRemoteNotification (null)

+ (unsigned int)_remoteNotificationServerPort;
+ (void)getSupportedBundleIdentifiers:(id*)arg1 enabledBundleIdentifiers:(id*)arg2;
+ (BOOL)isRegisteredForRemoteNotifications;
+ (unsigned char)legacyRegisteredRemoteNotificationTypes;
+ (void)registerForRemoteNotifications;
+ (void)registerForRemoteNotificationsWithLegacyTypes:(unsigned char)arg1;
+ (void)setAllowed:(BOOL)arg1 forBundleIdentifier:(id)arg2;
+ (void)unregisterForRemoteNotifications;

@end
