/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/libAVFAudio.dylib
 */

@interface AVAudioUnitEQ : AVAudioUnitEffect

@property (nonatomic, readonly) NSArray *bands;
@property (nonatomic) float globalGain;

// AVAudioUnitEQ (null)

- (id)bands;
- (float)globalGain;
- (id)init;
- (id)initWithNumberOfBands:(unsigned int)arg1;
- (void)setGlobalGain:(float)arg1;

@end
