/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/libAVFAudio.dylib
 */

@interface AVAudioUnitTimePitch : AVAudioUnitTimeEffect

@property (nonatomic) float overlap;
@property (nonatomic) float pitch;
@property (nonatomic) float rate;

// AVAudioUnitTimePitch (null)

- (id)init;
- (float)overlap;
- (float)pitch;
- (float)rate;
- (void)setOverlap:(float)arg1;
- (void)setPitch:(float)arg1;
- (void)setRate:(float)arg1;

@end
