/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/libAVFAudio.dylib
 */

@interface AVAudioIONode : AVAudioNode

@property (nonatomic, readonly) struct OpaqueAudioComponentInstance { }*audioUnit;
@property (nonatomic, readonly) double presentationLatency;

// AVAudioIONode (null)

- (struct OpaqueAudioComponentInstance { }*)audioUnit;
- (void)didAttachToEngine:(id)arg1;
- (void)didDetachFromEngine:(id)arg1;
- (double)presentationLatency;

@end
