/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/libAVFAudio.dylib
 */

@interface AVAudioUnitDistortion : AVAudioUnitEffect

@property (nonatomic) float preGain;
@property (nonatomic) float wetDryMix;

// AVAudioUnitDistortion (null)

- (struct AUPreset { int x1; struct __CFString {} *x2; })FillOutAUPreset:(int)arg1;
- (id)init;
- (void)loadFactoryPreset:(int)arg1;
- (float)preGain;
- (void)setPreGain:(float)arg1;
- (void)setWetDryMix:(float)arg1;
- (float)wetDryMix;

@end
