/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/libAVFAudio.dylib
 */

@interface AVAudioSessionRouteDescription : NSObject {
    void * _impl;
}

@property (readonly) NSArray *inputs;
@property (readonly) NSArray *outputs;

// AVAudioSessionRouteDescription (null)

+ (id)privateCreateOrConfigure:(id)arg1 withRawDescription:(id)arg2;

- (void)dealloc;
- (id)description;
- (id)init;
- (id)inputs;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isEqualToRoute:(id)arg1;
- (BOOL)matchesRawDescription:(id)arg1;
- (id)outputs;
- (struct RouteDescriptionImpl { id x1; }*)privateGetImplementation;

@end
