/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/libAVFAudio.dylib
 */

@interface AVAudioUnitReverb : AVAudioUnitEffect

@property (nonatomic) float wetDryMix;

// AVAudioUnitReverb (null)

- (id)init;
- (void)loadFactoryPreset:(int)arg1;
- (void)setWetDryMix:(float)arg1;
- (float)wetDryMix;

@end
