/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/libAVFAudio.dylib
 */

@interface AVSpeechSynthesizer : NSObject {
    <AVSpeechSynthesizerDelegate> * delegate;
    BOOL  paused;
    BOOL  speaking;
}

@property (nonatomic) <AVSpeechSynthesizerDelegate> *delegate;
@property (getter=isPaused, nonatomic, readonly) BOOL paused;
@property (getter=isSpeaking, nonatomic, readonly) BOOL speaking;

// AVSpeechSynthesizer (null)

+ (void)initialize;

- (BOOL)continueSpeaking;
- (id)delegate;
- (BOOL)isPaused;
- (BOOL)isSpeaking;
- (BOOL)pauseSpeakingAtBoundary:(int)arg1;
- (void)setDelegate:(id)arg1;
- (void)speakUtterance:(id)arg1;
- (BOOL)stopSpeakingAtBoundary:(int)arg1;

@end
