/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/libobjc.A.dylib
 */

@interface NSObject <NSObject> {
    Class  isa;
}

@property (nonatomic) struct CGPoint { float x1; float x2; } accessibilityActivationPoint;
@property (nonatomic, retain) NSArray *accessibilityCustomActions;
@property (nonatomic, retain) NSArray *accessibilityElements;
@property (nonatomic) BOOL accessibilityElementsHidden;
@property (nonatomic) struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; } accessibilityFrame;
@property (nonatomic, copy) NSArray *accessibilityHeaderElements;
@property (nonatomic, copy) NSString *accessibilityHint;
@property (nonatomic, copy) NSString *accessibilityIdentifier;
@property (nonatomic, copy) NSString *accessibilityLabel;
@property (nonatomic, retain) NSString *accessibilityLanguage;
@property (nonatomic) int accessibilityNavigationStyle;
@property (nonatomic, copy) UIBezierPath *accessibilityPath;
@property (nonatomic) unsigned long long accessibilityTraits;
@property (nonatomic, copy) NSString *accessibilityValue;
@property (nonatomic) BOOL accessibilityViewIsModal;
@property (readonly, retain) id autoContentAccessingProxy;
@property (readonly) Class classForKeyedArchiver;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned int hash;
@property (nonatomic) BOOL isAccessibilityElement;
@property void*observationInfo;
@property (nonatomic) BOOL shouldGroupAccessibilityChildren;
@property (readonly) Class superclass;
@property (getter=_traitStorageList, setter=_setTraitStorageList:, retain) _UITraitStorageList *traitStorageList;

// Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/libobjc.A.dylib

+ (BOOL)_isDeallocating;
+ (BOOL)_tryRetain;
+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone { }*)arg1;
+ (BOOL)allowsWeakReference;
+ (id)autorelease;
+ (Class)class;
+ (BOOL)conformsToProtocol:(id)arg1;
+ (id)copy;
+ (id)copyWithZone:(struct _NSZone { }*)arg1;
+ (void)dealloc;
+ (id)debugDescription;
+ (id)description;
+ (void)doesNotRecognizeSelector:(SEL)arg1;
+ (void)finalize;
+ (void)forwardInvocation:(id)arg1;
+ (id)forwardingTargetForSelector:(SEL)arg1;
+ (unsigned int)hash;
+ (id)init;
+ (void)initialize;
+ (int (*)instanceMethodForSelector:(SEL)arg1;
+ (id)instanceMethodSignatureForSelector:(SEL)arg1;
+ (BOOL)instancesRespondToSelector:(SEL)arg1;
+ (BOOL)isAncestorOfObject:(id)arg1;
+ (BOOL)isEqual:(id)arg1;
+ (BOOL)isFault;
+ (BOOL)isKindOfClass:(Class)arg1;
+ (BOOL)isMemberOfClass:(Class)arg1;
+ (BOOL)isProxy;
+ (BOOL)isSubclassOfClass:(Class)arg1;
+ (void)load;
+ (int (*)methodForSelector:(SEL)arg1;
+ (id)methodSignatureForSelector:(SEL)arg1;
+ (id)mutableCopy;
+ (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
+ (id)new;
+ (id)performSelector:(SEL)arg1;
+ (id)performSelector:(SEL)arg1 withObject:(id)arg2;
+ (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
+ (oneway void)release;
+ (BOOL)resolveClassMethod:(SEL)arg1;
+ (BOOL)resolveInstanceMethod:(SEL)arg1;
+ (BOOL)respondsToSelector:(SEL)arg1;
+ (id)retain;
+ (unsigned int)retainCount;
+ (BOOL)retainWeakReference;
+ (id)self;
+ (Class)superclass;
+ (struct _NSZone { }*)zone;

- (BOOL)_isDeallocating;
- (BOOL)_tryRetain;
- (BOOL)allowsWeakReference;
- (id)autorelease;
- (Class)class;
- (BOOL)conformsToProtocol:(id)arg1;
- (id)copy;
- (void)dealloc;
- (id)debugDescription;
- (id)description;
- (void)doesNotRecognizeSelector:(SEL)arg1;
- (void)finalize;
- (void)forwardInvocation:(id)arg1;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (unsigned int)hash;
- (id)init;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isFault;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isProxy;
- (int (*)methodForSelector:(SEL)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (id)mutableCopy;
- (id)performSelector:(SEL)arg1;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (oneway void)release;
- (BOOL)respondsToSelector:(SEL)arg1;
- (id)retain;
- (unsigned int)retainCount;
- (BOOL)retainWeakReference;
- (id)self;
- (Class)superclass;
- (struct _NSZone { }*)zone;

// Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation

// NSObject (NSObject)

+ (id)__allocWithZone_OA:(struct _NSZone { }*)arg1;
+ (id)_copyDescription;
+ (void)dealloc;
+ (id)description;
+ (void)doesNotRecognizeSelector:(SEL)arg1;
+ (void)finalize;
+ (id)init;
+ (id)instanceMethodSignatureForSelector:(SEL)arg1;
+ (void)load;
+ (id)methodSignatureForSelector:(SEL)arg1;

- (BOOL)___tryRetain_OA;
- (id)__autorelease_OA;
- (void)__dealloc_zombie;
- (oneway void)__release_OA;
- (id)__retain_OA;
- (id)_copyDescription;
- (id)description;
- (void)doesNotRecognizeSelector:(SEL)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;

// NSObject (__NSCFType)

- (unsigned long)_cfTypeID;

// NSObject (__NSIsKinds)

- (BOOL)isNSArray__;
- (BOOL)isNSData__;
- (BOOL)isNSDate__;
- (BOOL)isNSDictionary__;
- (BOOL)isNSNumber__;
- (BOOL)isNSOrderedSet__;
- (BOOL)isNSSet__;
- (BOOL)isNSString__;
- (BOOL)isNSTimeZone__;
- (BOOL)isNSValue__;

// Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Foundation

// NSObject (DefaultObservationImplementations)

- (BOOL)_isToManyChangeInformation;
- (id*)_observerStorage;
- (void)_receiveBox:(id)arg1;
- (id)addChainedObservers:(id)arg1;
- (id)addObservationTransformer:(id /* block */)arg1;
- (id)addObserver:(id)arg1;
- (id)addObserverBlock:(id /* block */)arg1;
- (void)finishObserving;
- (void)receiveObservedError:(id)arg1;
- (void)receiveObservedValue:(id)arg1;
- (void)removeObservation:(id)arg1;

// NSObject (KVOKeyPathSupport)

- (id)addObserver:(id)arg1 forObservableKeyPath:(id)arg2;
- (void)removeObservation:(id)arg1 forObservableKeyPath:(id)arg2;
- (void)setObservation:(id)arg1 forObservingKeyPath:(id)arg2;

// NSObject (NSArchiverCallBack)

- (Class)classForArchiver;
- (id)replacementObjectForArchiver:(id)arg1;

// NSObject (NSDOAdditions)

+ (struct objc_method_description { SEL x1; char *x2; }*)instanceMethodDescriptionForSelector:(SEL)arg1;
+ (struct objc_method_description { SEL x1; char *x2; }*)methodDescriptionForSelector:(SEL)arg1;

- (BOOL)_conformsToProtocolNamed:(const char *)arg1;
- (struct objc_method_description { SEL x1; char *x2; }*)methodDescriptionForSelector:(SEL)arg1;

// NSObject (NSDelayedPerforming)

+ (void)cancelPreviousPerformRequestsWithTarget:(id)arg1;
+ (void)cancelPreviousPerformRequestsWithTarget:(id)arg1 selector:(SEL)arg2 object:(id)arg3;

- (void)performSelector:(SEL)arg1 object:(id)arg2 afterDelay:(double)arg3;
- (void)performSelector:(SEL)arg1 withObject:(id)arg2 afterDelay:(double)arg3;
- (void)performSelector:(SEL)arg1 withObject:(id)arg2 afterDelay:(double)arg3 inModes:(id)arg4;

// NSObject (NSDeprecatedKeyValueObservingCustomization)

+ (void)setKeys:(id)arg1 triggerChangeNotificationsForDependentKey:(id)arg2;

// NSObject (NSDiscardableContentProxy)

- (id)autoContentAccessingProxy;

// NSObject (NSDistantObjectAdditions)

+ (const char *)_localClassNameForClass;

- (const char *)_localClassNameForClass;

// NSObject (NSKeyValueCoding)

+ (id)_createMutableArrayValueGetterWithContainerClassID:(id)arg1 key:(id)arg2;
+ (BOOL)accessInstanceVariablesDirectly;

- (id)dictionaryWithValuesForKeys:(id)arg1;
- (id)mutableArrayValueForKey:(id)arg1;
- (id)mutableArrayValueForKeyPath:(id)arg1;
- (id)mutableOrderedSetValueForKey:(id)arg1;
- (id)mutableOrderedSetValueForKeyPath:(id)arg1;
- (id)mutableSetValueForKey:(id)arg1;
- (id)mutableSetValueForKeyPath:(id)arg1;
- (void)setNilValueForKey:(id)arg1;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (void)setValue:(id)arg1 forKeyPath:(id)arg2;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (void)setValuesForKeysWithDictionary:(id)arg1;
- (BOOL)validateValue:(inout id*)arg1 forKey:(id)arg2 error:(out id*)arg3;
- (BOOL)validateValue:(inout id*)arg1 forKeyPath:(id)arg2 error:(out id*)arg3;
- (id)valueForKey:(id)arg1;
- (id)valueForKeyPath:(id)arg1;
- (id)valueForUndefinedKey:(id)arg1;

// NSObject (NSKeyValueCodingPrivate)

+ (id)_createMutableOrderedSetValueGetterWithContainerClassID:(id)arg1 key:(id)arg2;
+ (id)_createMutableSetValueGetterWithContainerClassID:(id)arg1 key:(id)arg2;
+ (id)_createOtherValueGetterWithContainerClassID:(id)arg1 key:(id)arg2;
+ (id)_createOtherValueSetterWithContainerClassID:(id)arg1 key:(id)arg2;
+ (id)_createValueGetterWithContainerClassID:(id)arg1 key:(id)arg2;
+ (id)_createValuePrimitiveGetterWithContainerClassID:(id)arg1 key:(id)arg2;
+ (id)_createValuePrimitiveSetterWithContainerClassID:(id)arg1 key:(id)arg2;
+ (id)_createValueSetterWithContainerClassID:(id)arg1 key:(id)arg2;

// NSObject (NSKeyValueObserverNotification)

- (void)didChange:(unsigned int)arg1 valuesAtIndexes:(id)arg2 forKey:(id)arg3;
- (void)didChangeValueForKey:(id)arg1;
- (void)didChangeValueForKey:(id)arg1 withSetMutation:(unsigned int)arg2 usingObjects:(id)arg3;
- (void)willChange:(unsigned int)arg1 valuesAtIndexes:(id)arg2 forKey:(id)arg3;
- (void)willChangeValueForKey:(id)arg1;
- (void)willChangeValueForKey:(id)arg1 withSetMutation:(unsigned int)arg2 usingObjects:(id)arg3;

// NSObject (NSKeyValueObserverNotifying)

- (BOOL)_isKVOA;

// NSObject (NSKeyValueObserverRegistration)

- (void)_addObserver:(id)arg1 forProperty:(id)arg2 options:(unsigned int)arg3 context:(void*)arg4;
- (void)_removeObserver:(id)arg1 forProperty:(id)arg2;
- (void)addObserver:(id)arg1 forKeyPath:(id)arg2 options:(unsigned int)arg3 context:(void*)arg4;
- (void)removeObserver:(id)arg1 forKeyPath:(id)arg2;
- (void)removeObserver:(id)arg1 forKeyPath:(id)arg2 context:(void*)arg3;

// NSObject (NSKeyValueObserving)

- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;

// NSObject (NSKeyValueObservingCustomization)

+ (id)_keysForValuesAffectingValueForKey:(id)arg1;
+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;

- (void*)observationInfo;
- (void)setObservationInfo:(void*)arg1;

// NSObject (NSKeyValueObservingPrivate)

+ (BOOL)_shouldAddObservationForwardersForKey:(id)arg1;

- (void)_changeValueForKey:(id)arg1 key:(id)arg2 key:(id)arg3 usingBlock:(id /* block */)arg4;
- (void)_changeValueForKey:(id)arg1 usingBlock:(id /* block */)arg2;
- (void)_didChangeValuesForKeys:(id)arg1;
- (id)_implicitObservationInfo;
- (void)_notifyObserversForKeyPath:(id)arg1 change:(id)arg2;
- (void)_willChangeValuesForKeys:(id)arg1;

// NSObject (NSKeyedArchiverObjectSubstitution)

+ (id)classFallbacksForKeyedArchiver;

- (Class)classForKeyedArchiver;
- (id)replacementObjectForKeyedArchiver:(id)arg1;

// NSObject (NSKeyedUnarchiverObjectSubstitution)

+ (Class)classForKeyedUnarchiver;

// NSObject (NSObject)

+ (BOOL)implementsSelector:(SEL)arg1;
+ (BOOL)instancesImplementSelector:(SEL)arg1;
+ (void)load;
+ (void)setVersion:(int)arg1;
+ (int)version;

- (BOOL)_allowsDirectEncoding;
- (id)awakeAfterUsingCoder:(id)arg1;
- (Class)classForCoder;
- (BOOL)implementsSelector:(SEL)arg1;
- (id)replacementObjectForCoder:(id)arg1;

// NSObject (NSObjectPortCoding)

+ (id)replacementObjectForPortCoder:(id)arg1;

- (Class)classForPortCoder;
- (id)replacementObjectForPortCoder:(id)arg1;

// NSObject (NSThreadPerformAdditions)

- (void)performSelector:(SEL)arg1 onThread:(id)arg2 withObject:(id)arg3 waitUntilDone:(BOOL)arg4;
- (void)performSelector:(SEL)arg1 onThread:(id)arg2 withObject:(id)arg3 waitUntilDone:(BOOL)arg4 modes:(id)arg5;
- (void)performSelectorInBackground:(SEL)arg1 withObject:(id)arg2;
- (void)performSelectorOnMainThread:(SEL)arg1 withObject:(id)arg2 waitUntilDone:(BOOL)arg3;
- (void)performSelectorOnMainThread:(SEL)arg1 withObject:(id)arg2 waitUntilDone:(BOOL)arg3 modes:(id)arg4;

// Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/QuartzCore.framework/QuartzCore

// NSObject (CAAnimatableValue)

- (id)CA_addValue:(id)arg1 multipliedBy:(int)arg2;
- (float)CA_distanceToValue:(id)arg1;
- (id)CA_interpolateValue:(id)arg1 byFraction:(float)arg2;
- (id)CA_interpolateValues:(id)arg1 :(id)arg2 :(id)arg3 interpolator:(const struct ValueInterpolator { double x1; double x2; double x3; double x4; double x5; double x6; double x7; double x8; double x9; bool x10; }*)arg4;
- (id)CA_roundToIntegerFromValue:(id)arg1;

// NSObject (CAMLWriter)

- (id)CAMLType;
- (id)CAMLTypeForKey:(id)arg1;
- (void)encodeWithCAMLWriter:(id)arg1;

// NSObject (CARenderValue)

- (struct Object { int (**x1)(); struct Atomic { struct { int x_1_2_1; } x_2_1_1; } x2; }*)CA_copyRenderValue;
- (void)CA_prepareRenderValue;

// NSObject (_CAObjectInternal)

+ (id)CA_CAMLPropertyForKey:(id)arg1;
+ (BOOL)CA_automaticallyNotifiesObservers:(Class)arg1;
+ (BOOL)CA_encodesPropertyConditionally:(unsigned int)arg1 type:(int)arg2;
+ (int (*)CA_getterForProperty:(const struct _CAPropertyInfo { unsigned int x1; SEL x2[2]; unsigned int x3 : 16; unsigned int x4 : 16; char *x5; struct __CFString {} *x6; }*)arg1;
+ (int (*)CA_setterForProperty:(const struct _CAPropertyInfo { unsigned int x1; SEL x2[2]; unsigned int x3 : 16; unsigned int x4 : 16; char *x5; struct __CFString {} *x6; }*)arg1;

// Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit

// NSObject (IvarDescription)

- (id)__ivarDescriptionForClass:(Class)arg1;
- (id)__methodDescriptionForClass:(Class)arg1;
- (id)_ivarDescription;
- (id)_methodDescription;
- (id)_shortMethodDescription;

// NSObject (NSLayoutConstraintCallsThis)

- (id)className;

// NSObject (UIAccessibility)

- (struct CGPoint { float x1; float x2; })accessibilityActivationPoint;
- (id)accessibilityContainer;
- (BOOL)accessibilityElementsHidden;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })accessibilityFrame;
- (id)accessibilityHeaderElements;
- (id)accessibilityHint;
- (id)accessibilityIdentifier;
- (id)accessibilityLabel;
- (id)accessibilityLanguage;
- (int)accessibilityNavigationStyle;
- (id)accessibilityPath;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityValue;
- (BOOL)accessibilityViewIsModal;
- (BOOL)isAccessibilityElement;
- (void)setAccessibilityActivationPoint:(struct CGPoint { float x1; float x2; })arg1;
- (void)setAccessibilityContainer:(id)arg1;
- (void)setAccessibilityElementsHidden:(BOOL)arg1;
- (void)setAccessibilityFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (void)setAccessibilityHeaderElements:(id)arg1;
- (void)setAccessibilityHint:(id)arg1;
- (void)setAccessibilityIdentifier:(id)arg1;
- (void)setAccessibilityLabel:(id)arg1;
- (void)setAccessibilityLanguage:(id)arg1;
- (void)setAccessibilityNavigationStyle:(int)arg1;
- (void)setAccessibilityPath:(id)arg1;
- (void)setAccessibilityTraits:(unsigned long long)arg1;
- (void)setAccessibilityValue:(id)arg1;
- (void)setAccessibilityViewIsModal:(BOOL)arg1;
- (void)setIsAccessibilityElement:(BOOL)arg1;
- (void)setShouldGroupAccessibilityChildren:(BOOL)arg1;
- (BOOL)shouldGroupAccessibilityChildren;
- (id)storedAccessibilityActivationPoint;
- (id)storedAccessibilityElementsHidden;
- (id)storedAccessibilityFrame;
- (id)storedAccessibilityNavigationStyle;
- (id)storedAccessibilityTraits;
- (id)storedAccessibilityViewIsModal;
- (id)storedIsAccessibilityElement;
- (id)storedShouldGroupAccessibilityChildren;

// NSObject (UIAccessibilityAction)

- (BOOL)accessibilityActivate;
- (id)accessibilityCustomActions;
- (void)accessibilityDecrement;
- (void)accessibilityIncrement;
- (BOOL)accessibilityPerformEscape;
- (BOOL)accessibilityPerformMagicTap;
- (BOOL)accessibilityScroll:(int)arg1;
- (void)setAccessibilityCustomActions:(id)arg1;

// NSObject (UIAccessibilityContainer)

- (id)accessibilityElementAtIndex:(int)arg1;
- (int)accessibilityElementCount;
- (id)accessibilityElements;
- (int)indexOfAccessibilityElement:(id)arg1;
- (void)setAccessibilityElements:(id)arg1;

// NSObject (UIAccessibilityFocus)

- (id)accessibilityAssistiveTechnologyFocusedIdentifiers;
- (void)accessibilityElementDidBecomeFocused;
- (void)accessibilityElementDidLoseFocus;
- (BOOL)accessibilityElementIsFocused;

// NSObject (UIAccessibilityPrivate)

+ (int)__accessibilityGuidedAccessRestrictionStateForIdentifier:(id)arg1;
+ (BOOL)__accessibilityGuidedAccessStateEnabled;
+ (void)__accessibilityRequestGuidedAccessSession:(BOOL)arg1 completion:(id /* block */)arg2;

- (void)_accessibilityFinalize;
- (void)accessibilitySetIdentification:(id)arg1;

// NSObject (UIAppearanceAdditions)

+ (void)_installAppearanceSwizzlesForSetter:(id)arg1;

// NSObject (UIKitAccessibilityInterfaceBuilderSupport)

- (unsigned long long)defaultAccessibilityTraits;
- (BOOL)isAccessibilityElementByDefault;
- (BOOL)isElementAccessibilityExposedToInterfaceBuilder;

// NSObject (UINibLoadingActionEstablishing)

- (void)_connectInterfaceBuilderEventConnection:(id)arg1;

// NSObject (UINibLoadingAdditions)

- (void)awakeFromNib;
- (void)prepareForInterfaceBuilder;

// NSObject (_NSItemProviderTypeCoercion_UIKitAdditions)

- (id)_NSItemProviderTypeCoercion_coercedUIImageValueFromNSDataValue:(id)arg1 error:(id*)arg2;
- (id)_NSItemProviderTypeCoercion_coercedUIImageValueFromNSURLValue:(id)arg1 error:(id*)arg2;

// NSObject (_UIApplicationAlternateUI)

+ (id)_alternateUISwitchableSelectorPairs;

// NSObject (_UIFocusPrivate)

- (id)_parentFocusEnvironment;
- (void)didUpdateFocusFromView:(id)arg1;
- (BOOL)shouldUpdateFocusFromView:(id)arg1 toView:(id)arg2 heading:(unsigned int)arg3;
- (void)willUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;
- (void)willUpdateFocusToView:(id)arg1;

// NSObject (_UITraitStorageAccessors)

- (void)_applyTraitStorageRecordsForTraitCollection:(id)arg1;
- (void)_setTraitStorageList:(id)arg1;
- (id)_traitStorageList;

// Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AppSupport.framework/AppSupport

// NSObject (null)

- (id)pep_afterDelay:(double)arg1;
- (id)pep_getInvocation:(id*)arg1;
- (id)pep_onDetachedThread;
- (id)pep_onMainThread;
- (id)pep_onMainThreadIfNecessary;
- (id)pep_onOperationQueue:(id)arg1;
- (id)pep_onOperationQueue:(id)arg1 priority:(int)arg2;
- (id)pep_onThread:(id)arg1;
- (id)pep_onThread:(id)arg1 immediateForMatchingThread:(BOOL)arg2;

// Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard

// NSObject (null)

+ (id)bs_dataFromObject:(id)arg1;
+ (id)bs_decodedFromData:(id)arg1;
+ (id)bs_objectFromData:(id)arg1;
+ (id)bs_secureDataFromObject:(id)arg1;
+ (id)bs_secureDecodedFromData:(id)arg1;
+ (id)bs_secureDecodedFromData:(id)arg1 withAdditionalClasses:(id)arg2;
+ (id)bs_secureObjectFromData:(id)arg1 ofClass:(Class)arg2;
+ (id)bs_secureObjectFromData:(id)arg1 ofClasses:(id)arg2;
+ (BOOL)bs_synchronousWrapper:(id /* block */)arg1 timeout:(double)arg2;

- (id)bs_encoded;
- (BOOL)bs_isPlistableType;
- (BOOL)bs_performSynchronously:(id /* block */)arg1;
- (BOOL)bs_performSynchronously:(id /* block */)arg1 timeout:(double)arg2;
- (id)bs_secureEncoded;

// Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/Celestial.framework/Celestial

// NSObject (NSObject_AVShared)

- (void)allowSafePerformSelector;
- (void)disallowSafePerformSelector;
- (void)fromMainThreadPostNotificationName:(id)arg1 object:(id)arg2 userInfo:(id)arg3;
- (void)fromNotifySafeThreadPerformSelector:(SEL)arg1 withObject:(id)arg2;
- (void)fromNotifySafeThreadPostNotificationName:(id)arg1 object:(id)arg2 userInfo:(id)arg3;
- (BOOL)okToNotifyFromThisThread;
- (void)postNotificationWithDescription:(id)arg1;

// Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/SpringBoardServices.framework/SpringBoardServices

// NSObject (null)

+ (id)sbs_dataFromObject:(id)arg1;
+ (id)sbs_dataWithValue:(id)arg1;
+ (id)sbs_objectFromData:(id)arg1;
+ (id)sbs_valueFromData:(id)arg1 ofType:(const char *)arg2;

- (BOOL)sbs_isPlistableType;

// Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore

// NSObject (WebCoreThreadAdditions)

- (void)releaseOnMainThread;

// Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy

// NSObject (null)

+ (id)_webkit_invokeOnMainThread;
+ (BOOL)isKeyExcludedFromWebScript:(const char *)arg1;
+ (BOOL)isSelectorExcludedFromWebScript:(SEL)arg1;

- (id)_webkit_invokeOnMainThread;

@end
