/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/libobjc.A.dylib
 */

@interface Object  {
    Class  isa;
}

+ (id)autorelease;
+ (id)class;
+ (id)initialize;
+ (void)release;
+ (id)retain;

- (id)autorelease;
- (void)release;
- (id)retain;

@end
