/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
 */

@interface _CUINineImagePieces : NSObject {
    CUIImage * _bottom;
    CUIImage * _bottomLeft;
    CUIImage * _bottomRight;
    CUIImage * _center;
    CUIImage * _left;
    CUIImage * _right;
    BOOL  _tileCenterAndEdges;
    CUIImage * _top;
    CUIImage * _topLeft;
    CUIImage * _topRight;
}

// _CUINineImagePieces (null)

- (id)bottom;
- (id)bottomLeft;
- (id)bottomRight;
- (id)center;
- (void)dealloc;
- (id)initWithCenter:(id)arg1 topLeft:(id)arg2 top:(id)arg3 topRight:(id)arg4 right:(id)arg5 bottomRight:(id)arg6 bottom:(id)arg7 bottomLeft:(id)arg8 left:(id)arg9 tileCenterAndEdges:(BOOL)arg10;
- (id)left;
- (id)right;
- (BOOL)tileCenterAndEdges;
- (id)top;
- (id)topLeft;
- (id)topRight;

@end
