/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
 */

@interface CUIPattern : NSObject {
    float  _alpha;
    struct CGPattern { } * _pattern;
    struct CGImage { } * _patternImage;
}

@property (nonatomic) float alpha;

// CUIPattern (null)

- (struct CGPattern { }*)_newPattern;
- (float)alpha;
- (void)dealloc;
- (id)description;
- (id)initWithImageRef:(struct CGImage { }*)arg1;
- (struct CGPattern { }*)pattern;
- (struct CGImage { }*)patternImageRef;
- (void)setAlpha:(float)arg1;
- (void)setPatternInContext:(struct CGContext { }*)arg1;

@end
