/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
 */

@interface CUIPSDLayer : NSObject {
    int  _blendMode;
    NSString * _name;
    float  _opacity;
}

@property (nonatomic) int blendMode;
@property (nonatomic, retain) NSString *name;
@property (nonatomic) float opacity;

// CUIPSDLayer (null)

- (int)blendMode;
- (void)dealloc;
- (id)init;
- (id)name;
- (float)opacity;
- (void)setBlendMode:(int)arg1;
- (void)setName:(id)arg1;
- (void)setOpacity:(float)arg1;

@end
