/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
 */

@interface CUIPSLayerEffectsPreset : CUIShapeEffectPreset

// CUIPSLayerEffectsPreset (null)

- (id)initWithLayerEffects:(id)arg1 forScaleFactor:(float)arg2;

@end
