/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
 */

@interface CUIPSDGradientLayer : CUIPSDLayer {
    CUIPSDGradient * _gradient;
}

@property (nonatomic, readonly) CUIPSDGradient *gradient;

// CUIPSDGradientLayer (null)

- (void)dealloc;
- (id)gradient;
- (id)initWithGradient:(id)arg1;

@end
