/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
 */

@interface CUIThemeSchemaPSDLayerGroup : CUIThemeSchemaPSDLayer {
    BOOL  isStart;
}

@property (nonatomic) BOOL isStart;

// CUIThemeSchemaPSDLayerGroup (null)

- (BOOL)isStart;
- (void)setIsStart:(BOOL)arg1;

@end
