/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
 */

@interface CUIThemeDataEffectPreset : CUIShapeEffectPreset

// CUIThemeDataEffectPreset (null)

- (id)description;
- (id)initWithEffectData:(const struct _cuieffectdata { unsigned int x1; unsigned int x2; unsigned int x3; unsigned int x4; struct _cuieffectlist { unsigned int x_5_1_1; unsigned int x_5_1_2[0]; } x5; }*)arg1 forScaleFactor:(float)arg2;

@end
