/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AudioToolbox.framework/AudioToolbox
 */

@interface AUParameterGroup : AUParameterNode <NSSecureCoding> {
    NSMutableDictionary * _childIndicesByIdentifier;
    NSArray * _children;
}

@property (nonatomic, readonly) NSArray *allParameters;
@property (nonatomic, retain) NSMutableDictionary *childIndicesByIdentifier;
@property (nonatomic, readonly) NSArray *children;

+ (BOOL)supportsSecureCoding;

- (void)_indexChildren;
- (void)_observersChanged:(BOOL)arg1 deltaCount:(int)arg2;
- (id)allParameters;
- (id)childIndicesByIdentifier;
- (id)children;
- (id)copyNodeWithOffset:(unsigned long long)arg1;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithChildren:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithID:(id)arg1 name:(id)arg2 children:(id)arg3;
- (id)initWithTemplate:(id)arg1 identifier:(id)arg2 name:(id)arg3 addressOffset:(unsigned long long)arg4;
- (BOOL)isGroup;
- (void)setChildIndicesByIdentifier:(id)arg1;
- (id)valueForKey:(id)arg1;

@end
