/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AudioToolbox.framework/AudioToolbox
 */

@interface AUV2BridgeBusArray : AUAudioUnitBusArray

- (id)initWithOwner:(id)arg1 scope:(unsigned long)arg2;
- (BOOL)isCountChangeable;
- (BOOL)setBusCount:(unsigned int)arg1 error:(id*)arg2;

@end
