/* Generated by RuntimeBrowser.
 */

@protocol _UIDocumentPickerServiceViewController <NSObject>

@required

- (void)didSelectItem:(_UIDocumentPickerContainerItem *)arg1;
- (int)displayMode;
- (void)setDisplayMode:(int)arg1;
- (void)setSortOrder:(int)arg1;
- (void)setupNavigationItemForPicker:(UINavigationItem *)arg1 isRoot:(BOOL)arg2;
- (BOOL)shouldShowSearch;
- (int)sortOrder;
- (NSURL *)uploadURL;

@optional

- (void)performAction:(void *)arg1 item:(void *)arg2 view:(void *)arg3 completion:(void *)arg4; // needs 4 arg types, found 8: int, _UIDocumentPickerContainerItem *, UIView *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, void*
- (void)renameItem:(void *)arg1 toName:(void *)arg2 completion:(void *)arg3; // needs 3 arg types, found 9: _UIDocumentPickerContainerItem *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, BOOL, BOOL, void*
- (void)selectionDidChange;
- (BOOL)shouldShowAction:(int)arg1;

@end
