/* Generated by RuntimeBrowser.
 */

@protocol _UIFocusEnvironmentInternal <UIFocusEnvironment>

@optional

- (<UIFocusEnvironment> *)_delegateFocusEnvironment;
- (void)_didUpdateFocusInContext:(UIFocusUpdateContext *)arg1 withAnimationCoordinator:(UIFocusAnimationCoordinator *)arg2;
- (BOOL)_shouldUpdateFocusInContext:(UIFocusUpdateContext *)arg1;
- (void)_willUpdateFocusInContext:(UIFocusUpdateContext *)arg1 withAnimationCoordinator:(UIFocusAnimationCoordinator *)arg2;

@end
