/* Generated by RuntimeBrowser.
 */

@protocol BSLogging <NSObject>

@required

- (BOOL)isEnabled;
- (void)logWithFormat:(NSString *)arg1;
- (void)logWithFormat:(NSString *)arg1 arguments:(char *)arg2;

@end
