/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/TextInput.framework/TextInput
 */

@interface TIKeyboardLayoutFactory : NSObject {
    NSMutableDictionary * _internalCache;
    void * _layoutsLibraryHandle;
}

@property (retain) NSMutableDictionary *internalCache;
@property (nonatomic, readonly) void*layoutsLibraryHandle;

+ (id)layoutsFileName;
+ (id)sharedKeyboardFactory;

- (void)dealloc;
- (id)init;
- (id)internalCache;
- (id)keyboardPrefixForWidth:(float)arg1 andEdge:(BOOL)arg2;
- (id)keyboardWithName:(id)arg1 inCache:(id)arg2;
- (void*)layoutsLibraryHandle;
- (void)setInternalCache:(id)arg1;

@end
