/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhysicsKit.framework/PhysicsKit
 */

@interface PKPhysicsFieldLinearGravity : PKPhysicsField

// PKPhysicsFieldLinearGravity (null)

+ (id)field;

- (void)direction;
- (id)init;
- (void)setDirection;

@end
