/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard
 */

@interface BSActionListener : BSBaseXPCServer {
    NSObject<OS_dispatch_queue> * _queue;
    NSMapTable * _queue_portToContextMap;
}

// BSActionListener (null)

- (void)_queue_cleanupContext:(struct { unsigned int x1; id x2; id /* block */ x3; }*)arg1 withResponse:(id)arg2;
- (void)clearListenerForTokens:(struct { unsigned int x1; id x2; /* Warning: Unrecognized filer type: '' using 'void*' */ void*x3; void*x4; void*x5; void*x6; void*x7; void*x8; void*x9; void*x10; void*x11; void*x12; void*x13; void*x14; void*x15; void*x16; void*x17; void*x18; void*x19; void*x20; out void*x21; void*x22; void*x23; void*x24; void*x25; void*x26; void*x27; void*x28; void*x29; void*x30; void*x31; void*x32; void*x33; void*x34; void*x35; Class x36; }*)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithServiceName:(id)arg1 onQueue:(id)arg2;
- (struct { unsigned int x1; id x2; /* Warning: Unrecognized filer type: '' using 'void*' */ void*x3; void*x4; void*x5; void*x6; void*x7; void*x8; void*x9; void*x10; void*x11; void*x12; void*x13; void*x14; void*x15; void*x16; void*x17; void*x18; void*x19; void x20; id x21; void*x22; void*x23; void*x24; unsigned int x25/* : ? */; void*x26; void*x27; void*x28; unsigned int x29/* : ? */; void*x30; void*x31; void*x32; void*x33; void*x34; void*x35; void*x36; void*x37; void*x38; void*x39; void*x40; unsigned int x41/* : ? */; void*x42; void*x43; void*x44; void*x45; void*x46; void*x47; void*x48; void*x49; void*x50; void*x51; void*x52; void*x53; })listenForResponseWithHandler:(id /* block */)arg1 timeout:(unsigned long long)arg2;
- (void)queue_handleMessage:(id)arg1 client:(id)arg2;

@end
