/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard
 */

@interface BSEventQueueEvent : NSObject {
    id /* block */  _handler;
    NSString * _name;
}

@property (nonatomic, copy) id /* block */ handler;
@property (nonatomic, copy) NSString *name;

// BSEventQueueEvent (null)

+ (id)eventWithName:(id)arg1 handler:(id /* block */)arg2;

- (void)_execute;
- (void)dealloc;
- (id)description;
- (void)execute;
- (void)executeFromEventQueue;
- (id /* block */)handler;
- (BOOL)isEqualToEvent:(id)arg1;
- (id)name;
- (void)setHandler:(id /* block */)arg1;
- (void)setName:(id)arg1;

@end
