/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard
 */

@interface BSMachPortReceiveRight : BSMachPortRight

// BSMachPortReceiveRight (null)

+ (void)_queue_destroyPort:(unsigned int)arg1;
+ (id)_rightDescription;
+ (BOOL)supportsSecureCoding;

- (id)_initWithPort:(unsigned int)arg1 previousTrace:(id)arg2;
- (BOOL)_queue_isUsable;
- (void)encodeWithCoder:(id)arg1;
- (void)encodeWithXPCDictionary:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithPort:(unsigned int)arg1;
- (id)initWithXPCDictionary:(id)arg1;

@end
