/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard
 */

@interface BSPlatform : NSObject

@property (nonatomic, readonly) BOOL hasGasGauge;
@property (nonatomic, readonly) BOOL hasOrbCapability;
@property (getter=isInternalInstall, nonatomic, readonly) BOOL internalInstall;
@property (nonatomic, readonly, copy) NSString *localizedProductName;
@property (getter=isMultiCore, nonatomic, readonly) BOOL multiCore;
@property (nonatomic, readonly, copy) NSString *productBuildVersion;
@property (nonatomic, readonly, copy) NSString *productClass;
@property (nonatomic, readonly, copy) NSString *productHardwareModel;
@property (nonatomic, readonly, copy) NSString *productType;
@property (nonatomic, readonly, copy) NSString *productVersion;
@property (nonatomic, readonly, copy) NSString *uniqueDeviceIdentifier;

// BSPlatform (null)

+ (id)sharedInstance;

- (BOOL)hasGasGauge;
- (BOOL)hasOrbCapability;
- (BOOL)isInternalInstall;
- (BOOL)isMultiCore;
- (id)localizedProductName;
- (id)productBuildVersion;
- (id)productClass;
- (id)productHardwareModel;
- (id)productType;
- (id)productVersion;
- (id)uniqueDeviceIdentifier;

@end
