/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard
 */

@interface BSStackFrameInfo : NSObject {
    unsigned long  _address;
    NSString * _className;
    NSString * _executableName;
    NSString * _functionName;
    NSString * _realFunctionName;
}

@property (nonatomic, readonly) unsigned long address;
@property (nonatomic, readonly, retain) NSString *className;
@property (nonatomic, readonly, retain) NSString *executableName;
@property (nonatomic, readonly, retain) NSString *functionName;

// BSStackFrameInfo (null)

- (unsigned long)address;
- (id)className;
- (void)dealloc;
- (id)description;
- (id)executableName;
- (id)functionName;
- (id)initWithReturnAddress:(unsigned long)arg1;

@end
