/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard
 */

@interface BSTimer : NSObject {
    double  _fireInterval;
    id /* block */  _handler;
    double  _leewayInterval;
    NSObject<OS_dispatch_queue> * _queue;
    double  _repeatInterval;
    BSDispatchSource * _source;
}

// BSTimer (null)

+ (id)scheduledTimerWithFireInterval:(double)arg1 queue:(id)arg2 handler:(id /* block */)arg3;

- (void)cancel;
- (void)dealloc;
- (id)initWithFireInterval:(double)arg1 queue:(id)arg2 handler:(id /* block */)arg3;
- (id)initWithFireInterval:(double)arg1 repeatInterval:(double)arg2 leewayInterval:(double)arg3 queue:(id)arg4 handler:(id /* block */)arg5;
- (void)schedule;

@end
