/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard
 */

@interface BSZeroingWeakReferenceProxy : NSProxy {
    Class  _targetClass;
    BSZeroingWeakReference * _weakReference;
}

// BSZeroingWeakReferenceProxy (null)

+ (id)zeroingWeakProxyWithObject:(id)arg1;

- (Class)class;
- (BOOL)conformsToProtocol:(id)arg1;
- (void)dealloc;
- (id)description;
- (void)forwardInvocation:(id)arg1;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (unsigned int)hash;
- (id)initWithObject:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;

@end
