/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AppSupport.framework/AppSupport
 */

@interface PEPServiceConfiguration : NSObject {
    NSString * _cacheFilePath;
    double  _cachedFileLastModifyDate;
    BOOL  _shouldDownloadNetworkConfigFile;
}

// PEPServiceConfiguration (null)

+ (id)sharedInstance;

- (void)_postNotification;
- (void)_updateDefaults:(id)arg1;
- (void)dealloc;
- (id)init;
- (BOOL)registerNetworkDefaultsForAppID:(id)arg1;
- (BOOL)registerNetworkDefaultsForAppIDs:(id)arg1 forceUpdate:(BOOL)arg2;

@end
