/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AppSupport.framework/AppSupport
 */

@interface ThreadedInvocationTrampoline : InvocationTrampoline {
    BOOL  _immediateForMatchingThread;
    NSThread * _thread;
}

// ThreadedInvocationTrampoline (null)

- (void)dealloc;
- (void)forwardInvocation:(id)arg1;
- (id)initWithTarget:(id)arg1 thread:(id)arg2 immediateForMatchingThread:(BOOL)arg3;

@end
