/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMAttr : DOMNode

@property (readonly, copy) NSString *name;
@property (readonly) DOMElement *ownerElement;
@property (readonly) BOOL specified;
@property (readonly) DOMCSSStyleDeclaration *style;
@property (copy) NSString *value;

- (BOOL)isId;
- (id)name;
- (id)ownerElement;
- (void)setValue:(id)arg1;
- (BOOL)specified;
- (id)style;
- (id)value;

@end
