/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMDocumentFragment : DOMNode

- (id)querySelector:(id)arg1;
- (id)querySelectorAll:(id)arg1;

@end
