/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMEntity : DOMNode

@property (readonly, copy) NSString *notationName;
@property (readonly, copy) NSString *publicId;
@property (readonly, copy) NSString *systemId;

- (id)notationName;
- (id)publicId;
- (id)systemId;

@end
