/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMFile : DOMBlob

@property (readonly, copy) NSString *name;

- (double)lastModifiedDate;
- (id)name;

@end
