/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMHTMLEmbedElement : DOMHTMLElement

@property (copy) NSString *align;
@property int height;
@property (copy) NSString *name;
@property (copy) NSString *src;
@property (copy) NSString *type;
@property int width;

// Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore

- (id)align;
- (int)height;
- (id)name;
- (void)setAlign:(id)arg1;
- (void)setHeight:(int)arg1;
- (void)setName:(id)arg1;
- (void)setSrc:(id)arg1;
- (void)setType:(id)arg1;
- (void)setWidth:(int)arg1;
- (id)src;
- (id)type;
- (int)width;

// Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit

// DOMHTMLEmbedElement (UIWebInteraction)

- (BOOL)showsTapHighlight;

@end
