/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMHTMLModElement : DOMHTMLElement

@property (copy) NSString *cite;
@property (copy) NSString *dateTime;

- (id)cite;
- (id)dateTime;
- (void)setCite:(id)arg1;
- (void)setDateTime:(id)arg1;

@end
