/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMHTMLMapElement : DOMHTMLElement

@property (readonly) DOMHTMLCollection *areas;
@property (copy) NSString *name;

- (id)areas;
- (id)name;
- (void)setName:(id)arg1;

@end
