/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMHTMLStyleElement : DOMHTMLElement

@property BOOL disabled;
@property (copy) NSString *media;
@property (readonly) DOMStyleSheet *sheet;
@property (copy) NSString *type;

- (BOOL)disabled;
- (id)media;
- (void)setDisabled:(BOOL)arg1;
- (void)setMedia:(id)arg1;
- (void)setType:(id)arg1;
- (id)sheet;
- (id)type;

@end
