/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMHTMLQuoteElement : DOMHTMLElement

@property (copy) NSString *cite;

- (id)cite;
- (void)setCite:(id)arg1;

@end
