/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMHTMLLabelElement : DOMHTMLElement

@property (copy) NSString *accessKey;
@property (readonly) DOMHTMLFormElement *form;
@property (copy) NSString *htmlFor;

- (id)accessKey;
- (id)control;
- (id)form;
- (id)htmlFor;
- (void)setAccessKey:(id)arg1;
- (void)setHtmlFor:(id)arg1;

@end
