/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMMediaList : DOMObject

@property (readonly) unsigned int length;
@property (copy) NSString *mediaText;

- (void)appendMedium:(id)arg1;
- (void)dealloc;
- (void)deleteMedium:(id)arg1;
- (void)finalize;
- (id)item:(unsigned int)arg1;
- (unsigned int)length;
- (id)mediaText;
- (void)setMediaText:(id)arg1;

@end
