/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMNodeList : DOMObject

@property (readonly) unsigned int length;

- (void)dealloc;
- (void)finalize;
- (id)item:(unsigned int)arg1;
- (unsigned int)length;

@end
