/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMPageTransitionEvent : DOMEvent

@property (readonly) BOOL persisted;

- (BOOL)persisted;

@end
