/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMRect : DOMObject

@property (readonly) DOMCSSPrimitiveValue *bottom;
@property (readonly) DOMCSSPrimitiveValue *left;
@property (readonly) DOMCSSPrimitiveValue *right;
@property (readonly) DOMCSSPrimitiveValue *top;

- (id)bottom;
- (void)dealloc;
- (void)finalize;
- (id)left;
- (id)right;
- (id)top;

@end
