/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMText : DOMCharacterData

@property (readonly, copy) NSString *wholeText;

- (id)replaceWholeText:(id)arg1;
- (id)splitText:(unsigned int)arg1;
- (id)wholeText;

@end
