/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface DOMWebKitAnimationEvent : DOMEvent

@property (readonly, copy) NSString *animationName;
@property (readonly) double elapsedTime;

- (id)animationName;
- (double)elapsedTime;

@end
