/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/SpringBoardServices.framework/SpringBoardServices
 */

@interface SBSAssertion : NSObject {
    NSString * _assertionName;
    struct _opaque_pthread_mutex_t { 
        long __sig; 
        BOOL __opaque[40]; 
    }  _lock;
    unsigned int  _port;
    NSString * _reason;
}

@property (nonatomic, readonly, copy) NSString *assertionName;
@property (nonatomic, readonly, copy) NSString *reason;

// SBSAssertion (null)

- (id)assertionName;
- (void)dealloc;
- (id)init;
- (id)initWithAssertionName:(id)arg1 reason:(id)arg2 port:(unsigned int)arg3;
- (void)invalidate;
- (id)reason;

@end
