/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/SpringBoardServices.framework/SpringBoardServices
 */

@interface SBSDisplayLayoutElement : FBSDisplayLayoutElement <SBSDisplayLayoutElement>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned int hash;
@property (nonatomic) int layoutRole;
@property (getter=isSpringBoardElement, nonatomic, readonly) BOOL springBoardElement;
@property (readonly) Class superclass;

// SBSDisplayLayoutElement (null)

- (id)initWithIdentifier:(id)arg1 layoutRole:(int)arg2;
- (BOOL)isSpringBoardElement;
- (int)layoutRole;
- (void)setLayoutRole:(int)arg1;
- (id)succinctDescriptionBuilder;

@end
