/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/SpringBoardServices.framework/SpringBoardServices
 */

@interface SBSLocalNotificationClient : NSObject

// SBSLocalNotificationClient (null)

+ (void)cancelAllLocalNotifications;
+ (void)cancelAllLocalNotificationsForBundleIdentifier:(id)arg1;
+ (void)cancelLocalNotification:(id)arg1;
+ (void)cancelLocalNotification:(id)arg1 bundleIdentifier:(id)arg2;
+ (void)cancelLocalNotification:(id)arg1 bundleIdentifier:(id)arg2 waitUntilDone:(BOOL)arg3;
+ (unsigned int)currentAllowedNotificationTypesForBundleID:(id)arg1;
+ (id)currentUserNotificationSettings;
+ (id)currentUserNotificationSettingsForBundleID:(id)arg1;
+ (void)migrateUserNotificationSettingsForBundleIdentifierPushSettingsPairs:(id)arg1;
+ (void)registerBadgePermissionForBundleIdentifier:(id)arg1;
+ (void)registerUserNotificationSettings:(id)arg1;
+ (void)registerUserNotificationSettings:(id)arg1 bundleIdentifier:(id)arg2;
+ (void)scheduleLocalNotification:(id)arg1;
+ (void)scheduleLocalNotification:(id)arg1 bundleIdentifier:(id)arg2;
+ (void)scheduleLocalNotification:(id)arg1 bundleIdentifier:(id)arg2 waitUntilDone:(BOOL)arg3;
+ (id)scheduledLocalNotifications;
+ (id)scheduledLocalNotificationsForBundleIdentifier:(id)arg1;
+ (void)setScheduledLocalNotifications:(id)arg1;
+ (void)setScheduledLocalNotifications:(id)arg1 bundleIdentifier:(id)arg2;

@end
