/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/SpringBoardServices.framework/SpringBoardServices
 */

@interface SBSRemoteNotificationClient : NSObject

// SBSRemoteNotificationClient (null)

+ (void)getSupportedBundleIdentifiers:(id*)arg1 enabledBundleIdentifiers:(id*)arg2;
+ (BOOL)isRegisteredForRemoteNotifications;
+ (unsigned char)legacyRegisteredRemoteNotificationTypes;
+ (void)registerForRemoteNotifications;
+ (void)registerForRemoteNotificationsWithLegacyTypes:(unsigned char)arg1;
+ (void)setAllowed:(BOOL)arg1 forBundleIdentifier:(id)arg2;
+ (void)unregisterForRemoteNotifications;

@end
