/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/system/libxpc.dylib
 */

@interface OS_xpc_object : OS_object <OS_xpc_object>

// OS_xpc_object (null)

- (void)_dispose;
- (void)_xref_dispose;
- (id)debugDescription;
- (id)description;
- (id)init;
- (id)retain;

@end
