/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/system/libxpc.dylib
 */

@interface OS_xpc_service_instance : OS_xpc_object <OS_xpc_service_instance>

// OS_xpc_service_instance (null)

+ (void)load;

@end
