/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
 */

@interface NSAttributeDictionaryEnumerator : NSEnumerator {
    NSAttributeDictionary * dictionary;
    unsigned int  nextElement;
}

// NSAttributeDictionaryEnumerator (null)

- (void)dealloc;
- (id)initWithAttributeDictionary:(id)arg1;
- (id)nextObject;

@end
