/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
 */

@interface NSGlyphNameGlyphInfo : NSIdentityGlyphInfo {
    NSString * _name;
}

// NSGlyphNameGlyphInfo (null)

+ (void)initialize;

- (void)dealloc;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)glyphName;
- (id)initWithCoder:(id)arg1;
- (id)initWithGlyphName:(id)arg1 glyph:(unsigned int)arg2 forFont:(id)arg3 baseString:(id)arg4;

@end
