/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
 */

@interface NSGlyphGenerator : NSObject

// NSGlyphGenerator (null)

+ (id)defaultGlyphGenerator;
+ (void)initialize;
+ (id)sharedGlyphGenerator;

- (void)generateGlyphsForGlyphStorage:(id)arg1 desiredNumberOfCharacters:(unsigned int)arg2 glyphIndex:(unsigned int*)arg3 characterIndex:(unsigned int*)arg4;

@end
