/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
 */

@interface NSParagraphArbitrator : NSObject {
    NSAttributedString * _attributedString;
    float  _hyphenationFactor;
    unsigned int  _lineBreakStrategy;
    id /* block */  _lineWidth;
    struct _NSRange { 
        unsigned int location; 
        unsigned int length; 
    }  _paragraphRange;
    int  _typesetterBehavior;
    id /* block */  _validateLineBreakContext;
}

@property (retain) NSAttributedString *attributedString;
@property float hyphenationFactor;
@property unsigned int lineBreakStrategy;
@property (copy) id /* block */ lineWidth;
@property struct _NSRange { unsigned int x1; unsigned int x2; } paragraphRange;
@property int typesetterBehavior;
@property (copy) id /* block */ validateLineBreakContext;

// NSParagraphArbitrator (null)

+ (id)paragraphArbitratorWithAttributedString:(id)arg1 range:(struct _NSRange { unsigned int x1; unsigned int x2; })arg2;

- (id)attributedString;
- (float)hyphenationFactor;
- (id)init;
- (id)initWithAttributedString:(id)arg1 range:(struct _NSRange { unsigned int x1; unsigned int x2; })arg2;
- (struct { unsigned int x1; unsigned int x2; BOOL x3; })lineBreakContextForProposedIndex:(unsigned int)arg1 lineFragmentWidth:(float)arg2 range:(struct _NSRange { unsigned int x1; unsigned int x2; })arg3;
- (unsigned int)lineBreakStrategy;
- (id /* block */)lineWidth;
- (struct _NSRange { unsigned int x1; unsigned int x2; })paragraphRange;
- (void)setAttributedString:(id)arg1;
- (void)setHyphenationFactor:(float)arg1;
- (void)setLineBreakStrategy:(unsigned int)arg1;
- (void)setLineWidth:(id /* block */)arg1;
- (void)setParagraphRange:(struct _NSRange { unsigned int x1; unsigned int x2; })arg1;
- (void)setTypesetterBehavior:(int)arg1;
- (void)setValidateLineBreakContext:(id /* block */)arg1;
- (int)typesetterBehavior;
- (id /* block */)validateLineBreakContext;

@end
