/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssertionServices.framework/AssertionServices
 */

@interface BKSProcessAssertionCreateResponseEvent : BKSProcessAssertionEvent {
    BOOL  _success;
}

@property (nonatomic) BOOL success;

// BKSProcessAssertionCreateResponseEvent (null)

- (id)description;
- (void)encodeWithXPCDictionary:(id)arg1;
- (id)initWithXPCDictionary:(id)arg1;
- (void)setSuccess:(BOOL)arg1;
- (BOOL)success;

@end
