/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssertionServices.framework/AssertionServices
 */

@interface BKSProcessAssertionUpdateEvent : BKSProcessAssertionEvent {
    unsigned int  _flags;
    NSString * _name;
}

@property (nonatomic) unsigned int flags;
@property (nonatomic, copy) NSString *name;

// BKSProcessAssertionUpdateEvent (null)

- (void)dealloc;
- (id)description;
- (void)encodeWithXPCDictionary:(id)arg1;
- (unsigned int)flags;
- (id)initWithXPCDictionary:(id)arg1;
- (id)name;
- (void)setFlags:(unsigned int)arg1;
- (void)setName:(id)arg1;

@end
