/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIAreaMinimum : CIAreaMaximum

- (id)_reduce1X4;
- (id)_reduce2X2;
- (id)_reduce4X1;

@end
