/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIBurstImageSet : NSObject {
    CIBurstImageSetInternal * _priv;
}

+ (id)burstImageSet;
+ (id)burstImageSetWithOptions:(id)arg1;
+ (id)defaultVersionString;

- (id)allImageIdentifiers;
- (id)bestImageIdentifiers;
- (id)burstId;
- (id)coverImageIdentifier;
- (void)dealloc;
- (unsigned int)imageClusterCount;
- (id)imageClusterForIdentifier:(id)arg1;
- (id)imageClusterForIndex:(unsigned int)arg1;
- (id)init;
- (id)initWithOptions:(id)arg1;
- (BOOL)isAction;
- (BOOL)isPortrait;
- (double)secondsSinceStart;
- (void)setLoggingListener:(void*)arg1 withUserInfo:(void*)arg2;
- (id)statsForImageWithIdentifier:(id)arg1;

@end
