/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIDisplacementDistortion : CIFilter {
    CIImage * inputDisplacementImage;
    CIImage * inputImage;
    NSNumber * inputScale;
}

+ (id)customAttributes;

- (id)_CIDisplaceFromImage;
- (id)outputImage;

@end
