/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIEdges : CIFilter {
    CIImage * inputImage;
    NSNumber * inputIntensity;
}

+ (id)customAttributes;

- (id)_CIEdges;
- (id)outputImage;

@end
