/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIFilterClassCategories : NSObject

+ (id)_categoriesWithClass:(Class)arg1;
+ (id)classCategoriesForClass:(Class)arg1;

@end
