/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIFourfoldRotatedTile : CITileFilter

- (id)_kernel_name;
- (id)_kernel_source;
- (id)outputImage;

@end
