/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIKaleidoscope : CIFilter {
    NSNumber * inputAngle;
    CIVector * inputCenter;
    NSNumber * inputCount;
    CIImage * inputImage;
}

+ (id)customAttributes;

- (id)_CIKaleidoscopeKernel:(int)arg1;
- (id)genFold:(id)arg1 aboutAngle:(float)arg2;
- (id)outputImage;

@end
