/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIPhotoEffect : CIFilter {
    CIImage * inputImage;
}

@property (nonatomic, retain) CIImage *inputImage;

+ (id)customAttributes;

- (int)_defaultVersion;
- (int)_maxVersion;
- (id)init;
- (id)inputImage;
- (id)outputImage;
- (void)setDefaults;
- (void)setInputImage:(id)arg1;

@end
