/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIProSharpenEdges : CIFilter {
    NSNumber * inputEdgeScale;
    NSNumber * inputFalloff;
    CIImage * inputImage;
    NSNumber * inputSharpness;
}

+ (id)customAttributes;

- (id)_CIBlur1;
- (id)_CIBlur2;
- (id)_CIBlur4;
- (id)_CIConvertRGBtoY;
- (id)_CIEdgesPrep;
- (id)_CIFindEdges;
- (id)_CISharpenCombineEdges;
- (id)outputImage;

@end
