/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIRAWTemperatureAdjust : CIFilter {
    NSNumber * inputEV;
    CIImage * inputImage;
    NSNumber * inputVersion;
    CIVector * inputWhitePoint;
}

- (id)outputImage;

@end
