/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreImage.framework/CoreImage
 */

@interface CIRAWGamutMapping : CIFilter {
    CIImage * inputImage;
    NSDictionary * inputRAWDictionary;
}

- (id)outputImage;

@end
