/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CFNetwork.framework/CFNetwork
 */

@interface __NSCFURLLocalStreamTaskWork : NSObject {
    const char * _static_description;
}

- (const char *)_static_description;
- (id)description;
- (id)initWithDescription:(const char *)arg1;

@end
