/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CFNetwork.framework/CFNetwork
 */

@interface __NSCFURLLocalStreamTaskWorkBlockOp : __NSCFURLLocalStreamTaskWork {
    id /* block */  _block;
}

+ (id)opWithBlock:(id /* block */)arg1 description:(const char *)arg2;

- (void)dealloc;
- (void)executeBlock;

@end
