/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CFNetwork.framework/CFNetwork
 */

@interface __NSURLAVBackgroundSession : __NSURLBackgroundSession

- (BOOL)isKindOfClass:(Class)arg1;

@end
