/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CFNetwork.framework/CFNetwork
 */

@interface _NSURLBDOnce : NSObject {
    id /* block */  fBlock;
    BOOL  fDone;
}

- (void)dealloc;
- (void)doit;
- (id)initWithBlock:(id /* block */)arg1;

@end
