/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CFNetwork.framework/CFNetwork
 */

@interface NSHTTPCookieStorage : NSObject {
    NSHTTPCookieStorageInternal * _internal;
}

@property unsigned int cookieAcceptPolicy;
@property (readonly, copy) NSArray *cookies;

+ (id)_groupContainerCookieStorages;
+ (id)_groupContainerStoragesLock;
+ (void)_setSharedHTTPCookieStorage:(id)arg1;
+ (id)_sharedCookieStorageLock;
+ (id)sharedCookieStorageForGroupContainerIdentifier:(id)arg1;
+ (id)sharedHTTPCookieStorage;

- (struct OpaqueCFHTTPCookieStorage { }*)_CFHTTPCookieStorage;
- (id)_cookiesForURL:(id)arg1 mainDocumentURL:(id)arg2;
- (unsigned int)cookieAcceptPolicy;
- (id)cookieRequestHeaderFieldsForURL:(id)arg1;
- (id)cookies;
- (id)cookiesForURL:(id)arg1;
- (void)dealloc;
- (void)deleteCookie:(id)arg1;
- (id)description;
- (void)getCookiesForTask:(id)arg1 completionHandler:(id /* block */)arg2;
- (id)init;
- (void)removeCookiesSinceDate:(id)arg1;
- (void)setCookie:(id)arg1;
- (void)setCookieAcceptPolicy:(unsigned int)arg1;
- (void)setCookies:(id)arg1 forURL:(id)arg2 mainDocumentURL:(id)arg3;
- (void)setCookiesFromResponseHeader:(id)arg1 forURL:(id)arg2 policyBaseURL:(id)arg3;
- (id)sortedCookiesUsingDescriptors:(id)arg1;
- (void)storeCookies:(id)arg1 forTask:(id)arg2;

// NSHTTPCookieStorage (NSPrivate)

- (struct OpaqueCFHTTPCookieStorage { }*)_cookieStorage;
- (id)_initWithCFHTTPCookieStorage:(struct OpaqueCFHTTPCookieStorage { }*)arg1;
- (id)_initWithIdentifier:(id)arg1 private:(bool)arg2;
- (void)_saveCookies;
- (void)_setPrivateBrowsingEnabled:(BOOL)arg1;

@end
