/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CFNetwork.framework/CFNetwork
 */

@interface NSHTTPCookieStorageInternal : NSObject {
    NSRecursiveLock * dataLock;
    BOOL  privateBrowsing;
    struct OpaqueCFHTTPCookieStorage { } * privateStorage;
    struct OpaqueCFHTTPCookieStorage { } * storage;
}

- (id)_initWithIdentifier:(id)arg1 private:(bool)arg2;
- (void)_syncCookies;
- (void)dealloc;
- (id)initInternalWithCFStorage:(struct OpaqueCFHTTPCookieStorage { }*)arg1;
- (void)registerForPostingNotifications;

@end
