/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CFNetwork.framework/CFNetwork
 */

@interface NSMutableURLRequest : NSURLRequest

@property (copy) NSData *HTTPBody;
@property (retain) NSInputStream *HTTPBodyStream;
@property (copy) NSString *HTTPMethod;
@property BOOL HTTPShouldHandleCookies;
@property BOOL HTTPShouldUsePipelining;
@property (copy) NSURL *URL;
@property (copy) NSDictionary *allHTTPHeaderFields;
@property BOOL allowsCellularAccess;
@property unsigned int cachePolicy;
@property (copy) NSURL *mainDocumentURL;
@property unsigned int networkServiceType;
@property double timeoutInterval;

// Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CFNetwork.framework/CFNetwork

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)setAllowsCellularAccess:(BOOL)arg1;
- (void)setBoundInterfaceIdentifier:(id)arg1;
- (void)setCachePolicy:(unsigned int)arg1;
- (void)setMainDocumentURL:(id)arg1;
- (void)setNetworkServiceType:(unsigned int)arg1;
- (void)setTimeoutInterval:(double)arg1;
- (void)setURL:(id)arg1;

// NSMutableURLRequest (NSMutableHTTPURLRequest)

- (void)_setPayloadTransmissionTimeout:(double)arg1;
- (void)_setRequiresShortConnectionTimeout:(BOOL)arg1;
- (void)_setStartTimeoutDate:(id)arg1;
- (void)_setTimeWindowDelay:(double)arg1;
- (void)_setTimeWindowDuration:(double)arg1;
- (void)addValue:(id)arg1 forHTTPHeaderField:(id)arg2;
- (unsigned int)requestPriority;
- (void)setAllHTTPHeaderFields:(id)arg1;
- (void)setContentDispositionEncodingFallbackArray:(id)arg1;
- (void)setExpectedWorkload:(unsigned long long)arg1;
- (void)setHTTPBody:(id)arg1;
- (void)setHTTPBodyStream:(id)arg1;
- (void)setHTTPContentType:(id)arg1;
- (void)setHTTPExtraCookies:(id)arg1;
- (void)setHTTPMethod:(id)arg1;
- (void)setHTTPReferrer:(id)arg1;
- (void)setHTTPShouldHandleCookies:(BOOL)arg1;
- (void)setHTTPShouldUsePipelining:(BOOL)arg1;
- (void)setHTTPUserAgent:(id)arg1;
- (void)setRequestPriority:(unsigned int)arg1;
- (void)setValue:(id)arg1 forHTTPHeaderField:(id)arg2;

// Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy

// NSMutableURLRequest (null)

- (void)_web_setHTTPContentType:(id)arg1;
- (void)_web_setHTTPReferrer:(id)arg1;
- (void)_web_setHTTPUserAgent:(id)arg1;

@end
