/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CFNetwork.framework/CFNetwork
 */

@interface NSURLCacheInternal : NSObject {
    struct _CFURLCache { struct __CFRuntimeBase { unsigned int x_1_1_1; unsigned char x_1_1_2[4]; } x1; struct __CFURLCache {} *x2; } * _cacheRef;
    unsigned int  currentDiskUsage;
    unsigned int  currentMemoryUsage;
    unsigned int  diskCapacity;
    NSString * diskPath;
    unsigned int  memoryCapacity;
}

- (void)dealloc;
- (void)finalize;

@end
