/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CFNetwork.framework/CFNetwork
 */

@interface NSURLProtocolInternal : NSObject {
    NSCachedURLResponse * cachedResponse;
    <NSURLProtocolClient> * client;
    NSLock * mutex;
    NSURLRequest * request;
}

- (void)dealloc;
- (id)init;

@end
