/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CFNetwork.framework/CFNetwork
 */

@interface NSURLResponseInternal : NSObject {
    struct _CFURLResponse { } * response;
}

- (void)dealloc;
- (id)initWithURLResponse:(struct _CFURLResponse { }*)arg1;

@end
