/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CFNetwork.framework/CFNetwork
 */

@interface NSURLDownloadInternal : NSObject {
    NSOperationQueue * _targetQueue;
    struct _CFURLDownload { } * cfDownload;
    struct _CFURLAuthChallenge { } * currCFChallenge;
    NSURLAuthenticationChallenge * currNSChallenge;
    id  delegate;
    BOOL  downloadActive;
}

- (void)dealloc;

@end
