/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

@interface __NSStackBlock : NSBlock

- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (unsigned int)retainCount;

@end
