/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

@interface __NSGenericDeallocHandler  {
    id /* block */  _block;
    Class  isa;
}

+ (void)initialize;

- (void)finalize;
- (void)release;
- (id)retain;
- (unsigned int)retainCount;

@end
