/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

@interface _CFXNotificationTokenRegistration : _CFXNotificationRegistrationBase {
    id /* block */  _handler;
    unsigned long  _options;
    id  _queue;
    BOOL  _registered;
    unsigned long long  _token;
}

@property (readonly, copy) id /* block */ handler;
@property (readonly) struct __CFString { }*name;
@property (readonly) void*object;
@property (readonly) void*observer;
@property (readonly) unsigned long options;
@property (retain) id queue;
@property (getter=isRegistered, readonly) BOOL registered;
@property (readonly) unsigned long long token;

+ (id)find:(unsigned long long)arg1;
+ (const struct { int x1; int (*x2)(); int (*x3)(); int (*x4)(); int (*x5)(); int (*x6)(); }*)keyCallbacks;
+ (void)remove:(unsigned long long)arg1;

- (void)_invalidate;
- (void)_removeFromParent;
- (void)addToObserver:(id)arg1;
- (id /* block */)copyHandler;
- (void)dealloc;
- (void)finalize;
- (id /* block */)handler;
- (id)initWithToken:(unsigned long long)arg1 options:(unsigned long)arg2 queue:(id)arg3 handler:(id /* block */)arg4;
- (void)invalidate;
- (BOOL)isRegistered;
- (void*)key;
- (struct __CFString { }*)name;
- (void*)object;
- (void*)observer;
- (unsigned long)options;
- (id)queue;
- (void)removeFromParent;
- (void)setQueue:(id)arg1;
- (unsigned long long)token;

@end
