/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

@interface _CFXNotificationRegistrationContainer : _CFXNotificationRegistrationBase {
    struct __CFDictionary { } * _children;
}

+ (Class)childClass;

- (void)addChild:(id)arg1;
- (void)dealloc;
- (BOOL)enumerate:(id /* block */)arg1;
- (void)finalize;
- (id)initWithParent:(id)arg1;
- (id)initWithParent:(id)arg1 childKeyCallbacks:(const struct { int x1; int (*x2)(); int (*x3)(); int (*x4)(); int (*x5)(); int (*x6)(); }*)arg2;
- (void)invalidate;
- (void)removeChild:(id)arg1;

@end
