/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

@interface _CFXNotificationNameWildcardObjectRegistration : _CFXNotificationNameRegistration

+ (Class)childClass;

- (id)acquireObject:(void*)arg1 options:(unsigned long)arg2;
- (id)acquireObserver:(void*)arg1 options:(unsigned long)arg2;
- (BOOL)enumerate:(id /* block */)arg1;
- (void)find:(void*)arg1 matching:(struct { id *x1; unsigned int x2; BOOL x3; }*)arg2;
- (void)match:(void*)arg1 matching:(struct { id *x1; unsigned int x2; BOOL x3; }*)arg2;
- (void)match:(void*)arg1 observer:(void*)arg2 matching:(struct { id *x1; unsigned int x2; BOOL x3; }*)arg3;

@end
