/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 */

@interface _CFXNotificationNameRegistration : _CFXNotificationRegistrationContainer {
    struct __CFString { } * _name;
}

@property (readonly) struct __CFString { }*name;

+ (Class)childClass;
+ (const struct { int x1; int (*x2)(); int (*x3)(); int (*x4)(); int (*x5)(); int (*x6)(); }*)keyCallbacks;

- (id)acquireObject:(void*)arg1;
- (void)dealloc;
- (BOOL)enumerate:(id /* block */)arg1;
- (void)finalize;
- (void)find:(void*)arg1 observer:(void*)arg2 matching:(struct { id *x1; unsigned int x2; BOOL x3; }*)arg3;
- (id)initWithName:(struct __CFString { }*)arg1 options:(unsigned long)arg2 parent:(id)arg3;
- (void*)key;
- (void)match:(void*)arg1 observer:(void*)arg2 matching:(struct { id *x1; unsigned int x2; BOOL x3; }*)arg3;
- (struct __CFString { }*)name;

@end
