/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/ConstantClasses.framework/ConstantClasses
 */

@interface _NSConstantDate : NSDate

// _NSConstantDate (null)

+ (id)alloc;
+ (void)load;

- (void)dealloc;
- (oneway void)release;
- (id)retain;
- (unsigned int)retainCount;
- (double)timeIntervalSinceReferenceDate;

@end
