/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
 */

@interface _WebSafeForwarder : NSObject {
    _WebSafeAsyncForwarder * asyncForwarder;
    long  asyncForwarderPred;
    id  defaultTarget;
    id  target;
}

// _WebSafeForwarder (null)

- (id)asyncForwarder;
- (void)clearTarget;
- (void)dealloc;
- (void)forwardInvocation:(id)arg1;
- (id)initWithTarget:(id)arg1 defaultTarget:(id)arg2;
- (id)methodSignatureForSelector:(SEL)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;

@end
