/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
 */

@interface WebHighlightLayer : CALayer {
    WebNodeHighlightView * _view;
    WebView * _webView;
}

// WebHighlightLayer (null)

- (id)actionForKey:(id)arg1;
- (id)initWithHighlightView:(id)arg1 webView:(id)arg2;
- (void)layoutSublayers;

@end
