/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
 */

@interface WebMainThreadInvoker : NSProxy {
    id  exception;
    id  target;
}

// WebMainThreadInvoker (null)

- (void)forwardInvocation:(id)arg1;
- (void)handleException:(id)arg1;
- (id)initWithTarget:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;

@end
