/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
 */

@interface WebPolicyDecisionListenerPrivate : NSObject {
    SEL  action;
    id  target;
}

// WebPolicyDecisionListenerPrivate (null)

- (void)dealloc;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;

@end
