/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
 */

@interface WebScriptWorldPrivate : NSObject {
    struct RefPtr<WebCore::DOMWrapperWorld> { 
        struct DOMWrapperWorld {} *m_ptr; 
    }  world;
}

// WebScriptWorldPrivate (null)

- (id).cxx_construct;
- (void).cxx_destruct;

@end
