/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
 */

@interface WebUndoStep : NSObject {
    struct RefPtr<WebCore::UndoStep> { 
        struct UndoStep {} *m_ptr; 
    }  m_step;
}

// WebUndoStep (null)

+ (void)initialize;
+ (id)stepWithUndoStep:(struct PassRefPtr<WebCore::UndoStep> { struct UndoStep {} *x1; })arg1;

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)dealloc;
- (void)finalize;
- (id)initWithUndoStep:(struct PassRefPtr<WebCore::UndoStep> { struct UndoStep {} *x1; })arg1;
- (struct UndoStep { int (**x1)(); unsigned int x2; }*)step;

@end
