/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

@interface CADisplayLink : NSObject {
    void * _impl;
}

@property (nonatomic, readonly) CADisplay *display;
@property (nonatomic, readonly) double duration;
@property (nonatomic) int frameInterval;
@property (getter=isPaused, nonatomic) BOOL paused;
@property (nonatomic, readonly) double timestamp;
@property (nonatomic, retain) id userInfo;

+ (id)displayLinkWithTarget:(id)arg1 selector:(SEL)arg2;

- (id)_initWithDisplayLinkItem:(struct DisplayLinkItem { struct Display {} *x1; void *x2; SEL x3; void *x4; int x5; struct Mutex { struct _opaque_pthread_mutex_t { long x_1_2_1; BOOL x_1_2_2[40]; } x_6_1_1; } x6; struct Condition { struct _opaque_pthread_cond_t { long x_1_2_1; BOOL x_1_2_2[24]; } x_7_1_1; } x7; struct _opaque_pthread_t {} *x8; id x9; /* Warning: Unrecognized filer type: 'R' using 'void*' */ void*x10; void*x11; float x12; void*x13; unsigned char x14; SEL x15; SEL x16; long doublex17; int x18; short x19; void*x20; long x21; void*x22; void*x23; SEL x24; SEL x25; long doublex26; int x27; short x28; void*x29; long x30; void*x31; void*x32; unsigned long x33; int x34; in void*x35; void*x36; void*x37; struct DisplayLink {} *x38; }*)arg1;
- (void)addToRunLoop:(id)arg1 forMode:(id)arg2;
- (void)dealloc;
- (double)duration;
- (int)frameInterval;
- (void)invalidate;
- (BOOL)isPaused;
- (void)removeFromRunLoop:(id)arg1 forMode:(id)arg2;
- (void)setFrameInterval:(int)arg1;
- (void)setPaused:(BOOL)arg1;
- (double)timestamp;

// CADisplayLink (CADisplayLinkPrivate)

+ (id)displayLinkWithDisplay:(id)arg1 target:(id)arg2 selector:(SEL)arg3;

- (id)display;
- (void)setUserInfo:(id)arg1;
- (id)userInfo;

@end
