/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/QuartzCore.framework/QuartzCore
 */

@interface CAMediaTimingFunctionBuiltin : CAMediaTimingFunction {
    unsigned int  _index;
}

- (void)_getPoints:(double*)arg1;
- (Class)classForCoder;
- (id)description;
- (void)encodeWithCAMLWriter:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end
