/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/system/libsystem_network.dylib
 */

@interface OS_nw_endpoint : OS_object

// OS_nw_endpoint (null)

- (void)_dispose;

@end
