/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/system/libsystem_network.dylib
 */

@interface OS_network_write_request : OS_object

// OS_network_write_request (null)

- (void)_dispose;

@end
