/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/system/libsystem_network.dylib
 */

@interface OS_tcp_connection_host : OS_object

// OS_tcp_connection_host (null)

- (void)_dispose;

@end
