/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIActivityPlaceholderItemProxy : NSProxy <NSCopying> {
    id  _placeholderItem;
}

- (void).cxx_destruct;
- (Class)class;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)forwardInvocation:(id)arg1;
- (unsigned int)hash;
- (id)initWithPlaceholderItem:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isProxy;
- (id)methodSignatureForSelector:(SEL)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;
- (Class)superclass;

@end
