/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIAlertControllerActionViewMetrics : NSObject {
    float  _descriptiveLabelTextWidth;
    float  _labelTextWidth;
}

@property (nonatomic) float descriptiveLabelTextWidth;
@property (nonatomic) float labelTextWidth;

- (float)descriptiveLabelTextWidth;
- (float)labelTextWidth;
- (void)setDescriptiveLabelTextWidth:(float)arg1;
- (void)setLabelTextWidth:(float)arg1;

@end
