/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIAlertControllerActionSheetRegularPresentationController : UIPopoverPresentationController

- (id)_alertController;
- (id)_alertControllerContainer;
- (id)_compactPresentationController;
- (id)_exceptionStringForNilSourceViewOrBarButtonItem;
- (id)_presentationControllerForTraitCollection:(id)arg1;
- (void)dimmingViewWasTapped:(id)arg1;

@end
