/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIAnimatedAttachmentView : UIView

+ (id)cacheKeyForAttachmentData:(id)arg1 name:(id)arg2;
+ (id)cachedObjectWithKey:(id)arg1 creationBlock:(id /* block */)arg2;

- (id)initWithAttachment:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;

@end
