/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIBackdropViewSettingsDark : _UIBackdropViewSettings

- (void)computeOutputSettingsUsingModel:(id)arg1;
- (void)setDefaultValues;

@end
