/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIBadgeTVVisualStyle : _UIBadgeVisualStyle

- (float)edgePadding;
- (float)fontSize;
- (float)horizontalInset;
- (float)maxWidth;
- (float)singleBadgeWidth;
- (BOOL)usesExternalImage;
- (float)verticalInset;

@end
