/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIBackdropViewSettingsUltraLight : _UIBackdropViewSettings

- (void)_accessibilityButtonShapesDidChangeNotification:(id)arg1;
- (void)computeOutputSettingsUsingModel:(id)arg1;
- (void)dealloc;
- (id)initWithDefaultValuesForGraphicsQuality:(int)arg1;
- (void)setDefaultValues;

@end
