/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UICollectionViewTrackedValueItem : NSObject {
    double  _timeStamp;
    float  _value;
}

@property (nonatomic) double timeStamp;
@property (nonatomic) float value;

- (void)setTimeStamp:(double)arg1;
- (void)setValue:(float)arg1;
- (double)timeStamp;
- (float)value;

@end
