/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UICollectionViewCompositionLayout : UICollectionViewLayout {
    NSMutableDictionary * _sublayoutsDict;
}

@property (nonatomic, readonly) NSArray *sublayouts;

+ (Class)invalidationContextClass;

- (void).cxx_destruct;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })_frameForLayout:(id)arg1 offset:(struct CGPoint { float x1; float x2; })arg2 relativeToEdges:(unsigned int)arg3 fromSiblingLayout:(id)arg4;
- (id)_originConvertedSublayoutAttributesForAttributes:(id)arg1 inLayout:(id)arg2;
- (void)_prepareLayout:(id)arg1;
- (void)addSublayout:(id)arg1 forElementKinds:(id)arg2;
- (void)addSublayout:(id)arg1 forItems:(id)arg2 inSection:(int)arg3 offset:(struct CGPoint { float x1; float x2; })arg4 relativeToEdges:(unsigned int)arg5 fromSiblingLayout:(id)arg6;
- (void)addSublayout:(id)arg1 forRect:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg2;
- (void)addSublayout:(id)arg1 forSections:(id)arg2 offset:(struct CGPoint { float x1; float x2; })arg3 relativeToEdges:(unsigned int)arg4 fromSiblingLayout:(id)arg5;
- (struct CGSize { float x1; float x2; })collectionViewContentSize;
- (id)init;
- (void)invalidateLayoutWithContext:(struct _UICollectionViewCompositionLayoutInvalidationContext { Class x1; id x2; /* Warning: Unrecognized filer type: '' using 'void*' */ void*x3; void*x4; void*x5; void*x6; void*x7; void*x8; void*x9; void*x10; void*x11; void*x12; void*x13; void*x14; void*x15; void*x16; out void*x17; void*x18; void*x19; void*x20; void*x21; void*x22; void*x23; void*x24; unsigned int x25; unsigned char x26; out long x27; long x28; void*x29; BOOL x30; void*x31; int x32; out in oneway int x33; void*x34; void*x35; unsigned char x36; out void*x37; void*x38; out short x39; int x40; void*x41; int x42; out in unsigned long x43; void*x44; void*x45; out void*x46; void*x47; unsigned int x48; in void x49; void*x50; long x51; int x52; double x53; void*x54; void*x55; int x56; out in unsigned char x57; out in void*x58; void*x59; void*x60; void*x61; void*x62; Class x63; id x64; void*x65; void*x66; void*x67; void*x68; void*x69; void*x70; void*x71; void*x72; void*x73; void*x74; void*x75; void*x76; void*x77; void*x78; unsigned char x79; void*x80; long x81; void*x82; void*x83; void*x84; short x85; void*x86; short x87; void*x88; void*x89; void*x90; int x91; void*x92; void*x93; void*x94; void*x95; void*x96; out void*x97; void*x98; void*x99; void*x100; void*x101; id x102; void*x103; void*x104; void*x105; void*x106; void*x107; void*x108; void*x109; inout void*x110; }*)arg1;
- (id)invalidationContextForBoundsChange:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (id)invalidationContextForPreferredLayoutAttributes:(id)arg1 withOriginalAttributes:(id)arg2;
- (id)layoutAttributesForDecorationViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)layoutAttributesForElementsInRect:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (void)prepareLayout;
- (void)removeSublayout:(id)arg1;
- (BOOL)shouldInvalidateLayoutForPreferredLayoutAttributes:(id)arg1 withOriginalAttributes:(id)arg2;
- (id)sublayouts;

@end
