/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UICAAnimationPositionQuantizer : NSObject

+ (id)animationWithQuantizedPositionsGivenAnimation:(id)arg1 appliedToView:(id)arg2;
+ (void)quantizePositionsInAnimation:(id)arg1 givenView:(id)arg2;

@end
