/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIDebugColorBoundsView : UIView

+ (id)_nextColor;

- (id)_colorViewBoundsOverlayCreateIfNecessary:(BOOL)arg1;
- (void)_removeColorViewBoundsOverlay;
- (void)doesNotRecognizeSelector:(SEL)arg1;
- (id)initWithView:(id)arg1;

@end
