/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIDynamicAnimationState : NSObject {
    NSMutableArray * _activeAnimations;
    CADisplayLink * _displayLink;
    double  _lastUpdateTime;
    UIScreen * _screen;
    BOOL  _shouldSchedYield;
    NSTimer * _timer;
}

@end
