/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIDocumentPickerDocumentTableCell : UITableViewCell <UITextFieldDelegate, _UIDocumentPickerDocumentTableCell, _UIDocumentPickerEditGrabberParent> {
    SKUIItemOfferButton * _cloudButton;
    UIView * _iconCenteringView;
    UIImageView * _iconView;
    _UIDocumentPickerContainerItem * _item;
    id  _progressSubscriber;
    NSTimer * _progressTimer;
    BOOL  _renamePending;
    UILabel * _subtitleLabel;
    _UIDocumentPickerDocumentTableViewController * _tableView;
    UIImageView * _tagView;
    NSLayoutConstraint * _tagViewCollapsingConstraint;
    _UIDocumentPickerCellEditGrabber * _titleEditGrabberView;
    UITextField * _titleTextField;
    NSLayoutConstraint * _titleTextFieldFullWidthConstraint;
}

@property (nonatomic, retain) SKUIItemOfferButton *cloudButton;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned int hash;
@property (nonatomic, retain) UIView *iconCenteringView;
@property (nonatomic, retain) UIImageView *iconView;
@property (nonatomic, retain) _UIDocumentPickerContainerItem *item;
@property (nonatomic, retain) id progressSubscriber;
@property (nonatomic, retain) NSTimer *progressTimer;
@property (nonatomic) BOOL renamePending;
@property (nonatomic, retain) UILabel *subtitleLabel;
@property (readonly) Class superclass;
@property (nonatomic) _UIDocumentPickerDocumentTableViewController *tableView;
@property (nonatomic, retain) UIImageView *tagView;
@property (nonatomic, retain) NSLayoutConstraint *tagViewCollapsingConstraint;
@property (nonatomic, retain) _UIDocumentPickerCellEditGrabber *titleEditGrabberView;
@property (nonatomic, retain) UITextField *titleTextField;
@property (nonatomic, retain) NSLayoutConstraint *titleTextFieldFullWidthConstraint;

+ (struct CGSize { float x1; float x2; })thumbnailSize;

- (void).cxx_destruct;
- (id)cloudButton;
- (void)dealloc;
- (id)iconCenteringView;
- (id)iconView;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (id)item;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (id)progressSubscriber;
- (id)progressTimer;
- (void)reloadItem:(BOOL)arg1;
- (BOOL)renamePending;
- (void)setCloudButton:(id)arg1;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setIconCenteringView:(id)arg1;
- (void)setIconView:(id)arg1;
- (void)setItem:(id)arg1;
- (void)setProgressSubscriber:(id)arg1;
- (void)setProgressTimer:(id)arg1;
- (void)setRenamePending:(BOOL)arg1;
- (void)setSubtitleLabel:(id)arg1;
- (void)setTableView:(id)arg1;
- (void)setTagView:(id)arg1;
- (void)setTagViewCollapsingConstraint:(id)arg1;
- (void)setTitleEditGrabberView:(id)arg1;
- (void)setTitleTextField:(id)arg1;
- (void)setTitleTextFieldFullWidthConstraint:(id)arg1;
- (void)startDownload:(id)arg1;
- (id)subtitleLabel;
- (id)tableView;
- (id)tagView;
- (id)tagViewCollapsingConstraint;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (BOOL)textFieldShouldBeginEditing:(id)arg1;
- (BOOL)textFieldShouldEndEditing:(id)arg1;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (id)titleEditGrabberView;
- (id)titleTextField;
- (id)titleTextFieldFullWidthConstraint;
- (void)updateForDownloadStatus;
- (void)updateProgress:(id)arg1;

@end
