/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIDictationPrivacySheetController : UINavigationController {
    id /* block */  _dismissHandler;
}

@property (copy) id /* block */ dismissHandler;

+ (id)controllerWithDismissHandler:(id /* block */)arg1;

- (void)dismiss;
- (id /* block */)dismissHandler;
- (id)initWithHandler:(id /* block */)arg1;
- (void)setDismissHandler:(id /* block */)arg1;

@end
