/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIDocumentPickerFlowLayout : UICollectionViewFlowLayout {
    float  _contentSizeAdjustment;
}

@property (nonatomic) float contentSizeAdjustment;

- (struct CGSize { float x1; float x2; })collectionViewContentSize;
- (float)contentSizeAdjustment;
- (void)setContentSizeAdjustment:(float)arg1;

@end
