/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIEstimatedTouchRecord : NSObject {
    UITouch * _frozenTouch;
    UITouch * _liveTouch;
    NSMutableArray * _touchables;
}

@property (readonly, retain) UITouch *frozenTouch;
@property (readonly, retain) UITouch *liveTouch;
@property (readonly, retain) NSArray *touchables;

- (void).cxx_destruct;
- (void)addTouchable:(id)arg1;
- (id)frozenTouch;
- (id)initWithLiveTouch:(id)arg1 freezeTouch:(id)arg2;
- (id)liveTouch;
- (void)removeTouchable:(id)arg1;
- (id)touchables;

@end
