/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIFocusableRegionMapEntry : _UIFocusRegionMapEntry <NSSecureCoding> {
    <_UIFocusRegion> * _focusableRegion;
}

@property (nonatomic, retain) <_UIFocusRegion> *focusableRegion;

- (void).cxx_destruct;
- (id)description;
- (id)focusableRegion;
- (void)setFocusableRegion:(id)arg1;

@end
