/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIFallbackPresentationWindow : UIWindow

+ (BOOL)_isSystemWindow;

- (BOOL)_canAffectStatusBarAppearance;
- (BOOL)_includeInDefaultImageSnapshot;

@end
