/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIFocusViewSearchResult : NSObject {
    UIFocusUpdateContext * _focusCandidate;
    BOOL  _hasSpeedBump;
}

@property (nonatomic, retain) UIFocusUpdateContext *focusCandidate;
@property (nonatomic) BOOL hasSpeedBump;

- (void).cxx_destruct;
- (id)focusCandidate;
- (BOOL)hasSpeedBump;
- (void)setFocusCandidate:(id)arg1;
- (void)setHasSpeedBump:(BOOL)arg1;

@end
