/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIGameControllerEvent : UIEvent {
    struct { 
        float controllerState[16]; 
        float normalizedLeftStickState[4]; 
        BOOL didSendEvent; 
        BOOL dPadActive; 
        BOOL leftStickActive; 
    }  previousState;
}

- (struct CGPoint { float x1; float x2; })_leftStickPosition;
- (void)_maybeConvertAndSendAsPressesEvent;
- (void)_sendEventToResponder:(id)arg1;
- (int)subtype;
- (int)type;

@end
