/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIImageViewPretiledImageWrapper : NSObject {
    _UIImageViewPretiledImageCacheKey * _cacheKey;
    UIImage * _pretiledImage;
}

@property (nonatomic, readonly) UIImage *pretiledImage;

+ (id)cacheValueWithPretiledImage:(id)arg1 cacheKey:(id)arg2;

- (void).cxx_destruct;
- (void)dealloc;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)pretiledImage;

@end
