/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIKeyboardBasedTextSelectionGestureController : _UIKeyboardTextSelectionGestureController

+ (id)sharedInstance;

- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;

@end
