/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UILongDefinitionViewController : UIViewController {
    _UIDefinitionValue * _definitionValue;
}

- (void).cxx_destruct;
- (id)initWithDefinitionValue:(id)arg1;
- (void)viewDidLoad;

@end
