/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UILayerHostView : UIView

@property (nonatomic) unsigned int contextID;
@property (nonatomic) BOOL inheritsSecurity;
@property (nonatomic, readonly, retain) CALayerHost *layerHost;

+ (Class)layerClass;

- (void)_compensateForGlobalMediaTimeAdjustmentsIfNecessary;
- (void)_didMoveFromWindow:(id)arg1 toWindow:(id)arg2;
- (void)_snapshotAdjustedMediaTiming:(id)arg1;
- (unsigned int)contextID;
- (void)dealloc;
- (BOOL)inheritsSecurity;
- (id)layerHost;
- (void)setContextID:(unsigned int)arg1;
- (void)setInheritsSecurity:(BOOL)arg1;

@end
