/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UILegibilityImageView : UIImageView

- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)setImage:(id)arg1;

@end
