/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UILabelContentLayer : CALayer

- (id)actionForKey:(id)arg1;
- (void)drawInContext:(struct CGContext { }*)arg1;

@end
