/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIModalItemAccessoryViewControllerForLegacyAlert : UIViewController {
    UIView * _accessoryView;
}

- (void)_setAccessoryView:(id)arg1;
- (void)dealloc;
- (void)viewWillAppear:(BOOL)arg1;

@end
