/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIMotionEffectCoreMotionEventProvider : _UIMotionEffectEventProvider {
    NSOperationQueue * _motionEventQueue;
    CMMotionManager * _motionManager;
}

- (void).cxx_destruct;
- (id)currentEvent;
- (void)dealloc;
- (double)fastUpdateIntervalForLogs;
- (id)init;
- (void)setSlowUpdatesEnabled:(BOOL)arg1;
- (BOOL)shouldLogEvents;
- (double)slowUpdateIntervalForLogs;
- (void)startGeneratingEvents;
- (void)stopGeneratingEvents;

@end
