/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UINavigationBarStarkVisualStyle : _UINavigationBarVisualStyle

- (float)backIndicatorBottomMargin;
- (float)buttonHeight;
- (float)leftBackTitleMargin;
- (float)leftTitleMargin;
- (int)navigationBar:(id)arg1 metricsForOrientation:(int)arg2 hasPrompt:(BOOL)arg3;
- (BOOL)shouldForceLegacyLeftBackTitleMarginForView:(id)arg1 withCustomBackButtonBackground:(id)arg2 useAdditionalLetterpressPadding:(BOOL)arg3;
- (float)topMargin;
- (float)topTitleMargin;

@end
