/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UINavigationBarTVVisualStyle : _UINavigationBarVisualStyle

- (float)barHeight;
- (struct UIEdgeInsets { float x1; float x2; float x3; float x4; })buttonContentEdgeInsets;
- (float)buttonHeight;
- (float)buttonImagePadding;
- (float)interItemSpace;
- (float)leftTitleMargin;
- (float)navigationItemBaselineOffset;
- (float)topMargin;

@end
