/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIStoryboardUnwindChain : NSObject {
    unsigned int  _commonAncestorIdx;
    unsigned int  _modalAncestorContainingSourceIdx;
    NSMutableArray * _viewControllers;
}

@property (nonatomic, readonly) UIViewController *commonAncestorViewController;
@property (nonatomic, readonly) UIViewController *modalAncestorContainingSourceViewController;

- (void).cxx_destruct;
- (id)commonAncestorViewController;
- (id)debugDescription;
- (void)enumerateViewControllersFromModalAncestorUpToButNotIncludingDestination:(id /* block */)arg1;
- (id)initFromSourceViewController:(id)arg1 toDestinationViewController:(id)arg2;
- (id)modalAncestorContainingSourceViewController;

@end
