/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UITabBarItemAppearanceStorage : _UIBarItemAppearanceStorage {
    NSValue * titleOffset;
}

@property (nonatomic, retain) NSValue *titleOffset;

- (void)dealloc;
- (void)setTitleOffset:(id)arg1;
- (id)titleOffset;

@end
