/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UITextInputControllerLayoutManagerConnection : NSObject {
    UITextInputController * _textInputController;
}

@property (nonatomic, retain) UITextInputController *textInputController;

- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithTextInputController:(id)arg1;
- (void)setTextInputController:(id)arg1;
- (id)textInputController;

@end
