/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UITableViewDeleteAnimationSupport : NSObject {
    NSMutableArray * _cellsToDeleteAfterAnimation;
    int  _deleteCount;
    unsigned int  _enabledStateBeforeDeleteAnimation;
    unsigned int  _reserved;
}

- (void).cxx_destruct;

@end
