/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UITraitBasedAppearance : _UIAppearance {
    UITraitCollection * _traitCollection;
}

+ (id)_appearanceForTraitCollection:(id)arg1 forClass:(Class)arg2 withContainerList:(id)arg3;
+ (BOOL)_hasAnyCustomizations;
+ (BOOL)_hasCustomizationsForTraitCollection:(id)arg1 class:(Class)arg2 guideClass:(Class)arg3;
+ (void)_setHasAnyCustomizations;

- (void)_invalidateAppearanceInWindow:(id)arg1;
- (BOOL)_isValidAppearanceForCustomizableObject:(id)arg1;
- (id)_traitCollection;
- (void)dealloc;

@end
