/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UITableViewReorderingSupport : NSObject {
    NSTimer * _autoscrollTimer;
    UIShadowView * _bottomShadowView;
    NSIndexPath * _initialIndexPath;
    unsigned int  _oldShowHorizontalScrollIndicator;
    unsigned int  _oldShowVerticalScrollIndicator;
    unsigned int  _reloadDataCalled;
    UITableViewCell * _reorderedCell;
    unsigned int  _reorderingCancelled;
    unsigned int  _reserved;
    NSIndexPath * _targetIndexPath;
    UIShadowView * _topShadowView;
    BOOL  _wasScrollingEnabled;
}

- (void).cxx_destruct;

@end
