/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UITableViewHeaderFooterViewBackground : UIView {
    UIView * _opaqueBackgroundView;
    UIView * _transparentBackgroundView;
}

- (void).cxx_destruct;
- (id)_opaqueBackgroundView;
- (id)_transparentBackgroundView;
- (void)_updateBackingView;
- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (void)setBackgroundImage:(id)arg1;
- (void)setOpaque:(BOOL)arg1;

@end
