/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UITouchPredictionManager : NSObject

- (id)predictedTouchesForObservedTouches:(id)arg1 scale:(float)arg2;

@end
