/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIViewServiceDummyPopoverBackgroundView : UIPopoverBackgroundView {
    unsigned int  arrowDirection;
    float  arrowOffset;
}

+ (float)arrowBase;
+ (float)arrowHeight;
+ (struct UIEdgeInsets { float x1; float x2; float x3; float x4; })contentViewInsets;
+ (BOOL)wantsDefaultContentAppearance;

- (struct CGSize { float x1; float x2; })_shadowOffset;
- (float)_shadowOpacity;
- (float)_shadowRadius;
- (unsigned int)arrowDirection;
- (float)arrowOffset;
- (void)setArrowDirection:(unsigned int)arg1;
- (void)setArrowOffset:(float)arg1;

@end
