/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIViewAdditiveAnimationAction : NSObject <CAAction> {
    CAAnimation * _pendingAnimation;
}

@property (nonatomic, readonly, retain) CAAnimation *pendingAnimation;

- (void).cxx_destruct;
- (id)initWithPendingAnimation:(id)arg1;
- (id)pendingAnimation;
- (void)runActionForKey:(id)arg1 object:(id)arg2 arguments:(id)arg3;

@end
