/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIViewServiceDummyPopoverView : _UIPopoverView

- (void)setUseToolbarShine:(BOOL)arg1;

@end
