/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIViewServiceReplyControlTrampoline : _UITargetedProxy

- (void)_forwardInvocation:(id)arg1 withIncomingReplyDispatchBlock:(id /* block */)arg2;
- (void)forwardInvocation:(id)arg1;

@end
