/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface _UIViewServiceViewControllerDeputy : _UITargetedProxy <_UIViewServiceDeputy>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned int hash;
@property (readonly) Class superclass;

+ (id)XPCInterface;
+ (id)deputyWithViewController:(id)arg1;

- (void)__prepareForDisconnectionWithCompletionHandler:(id /* block */)arg1;
- (id)invalidate;

@end
