/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface EmojiSectionHeaderLayoutInvalidationContext : UICollectionViewFlowLayoutInvalidationContext {
    struct __CFDictionary { } * _headerWidthDict;
    NSMutableIndexSet * _invalidatedSections;
}

@property (nonatomic, readonly) NSIndexSet *invalidatedSections;

- (void)dealloc;
- (id)invalidatedSections;
- (float)preferredWidthForHeaderInSection:(int)arg1;

@end
