/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface NSDocumentDifferenceSizeTriple : NSObject {
    NSDocumentDifferenceSize * _betweenPreservingPreviousVersionAndSaving;
    NSDocumentDifferenceSize * _betweenPreviousSavingAndSaving;
    NSDocumentDifferenceSize * _dueToRecentChangesBeforeSaving;
}

@property (nonatomic, readonly) NSDocumentDifferenceSize *betweenPreservingPreviousVersionAndSaving;
@property (nonatomic, readonly) NSDocumentDifferenceSize *betweenPreviousSavingAndSaving;
@property (nonatomic, readonly) NSDocumentDifferenceSize *dueToRecentChangesBeforeSaving;

- (void).cxx_destruct;
- (id)betweenPreservingPreviousVersionAndSaving;
- (id)betweenPreviousSavingAndSaving;
- (id)description;
- (id)dueToRecentChangesBeforeSaving;
- (id)init;

@end
