/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIAlertMediaButton : UIAlertButton {
    UIImageView * _checkmarkView;
    UIImage * _highlightedTableIcon;
    UIImage * _tableIcon;
}

@property (nonatomic, readonly) UIImageView *checkmarkView;
@property (nonatomic, retain) UIImage *highlightedTableIcon;
@property (nonatomic, retain) UIImage *tableIcon;

- (id)checkmarkView;
- (void)dealloc;
- (id)highlightedTableIcon;
- (void)layoutSubviews;
- (void)setHighlightedTableIcon:(id)arg1;
- (void)setTableIcon:(id)arg1;
- (id)tableIcon;

@end
