/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIAlphaAnimation : UIAnimation {
    float  _endAlpha;
    float  _startAlpha;
}

- (float)_alphaForMultiplier:(float)arg1;
- (float)alphaForFraction:(float)arg1;
- (void)setEndAlpha:(float)arg1;
- (void)setProgress:(float)arg1;
- (void)setStartAlpha:(float)arg1;

@end
