/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIAlertControllerVisualStyleAlertTV : UIAlertControllerVisualStyleAlert

- (id)_detailMessageFont;
- (float)_marginAboveDetailMessageFirstBaseline;
- (id)actionContentColorForAction:(id)arg1 withViewRepresentation:(id)arg2 inAlertController:(id)arg3;
- (float)actionHorizontalContentMargin;
- (float)actionWidthForMinimumActionWidth:(float)arg1;
- (float)backgroundCornerRadius;
- (id)backgroundView;
- (id)backgroundViewForAction:(id)arg1 withViewRepresentation:(id)arg2 inAlertController:(id)arg3;
- (struct UIEdgeInsets { float x1; float x2; float x3; float x4; })collectionViewContentInsets;
- (struct CGSize { float x1; float x2; })collectionViewOutsetSize;
- (struct UIEdgeInsets { float x1; float x2; float x3; float x4; })contentInsets;
- (id)dimmingViewForAlertController:(id)arg1;
- (BOOL)focusedActionAnimatesOnPresentationAndDismissal;
- (BOOL)hideActionSeparators;
- (BOOL)hideCancelAction:(id)arg1 inAlertController:(id)arg2;
- (struct CGAffineTransform { float x1; float x2; float x3; float x4; float x5; float x6; })highlightedActionTransformForActionSize:(struct CGSize { float x1; float x2; })arg1;
- (float)marginAboveTitleLabelFirstBaseline;
- (float)marginBelowLastLabelLastBaseline;
- (float)marginBelowMessageLabelLastBaseline;
- (float)marginBelowTitleLabelLastBaseline;
- (float)maximumWidth;
- (float)maximumWidthForTitleAndMessageContentView;
- (id)messageLabelColor;
- (id)messageLabelFont;
- (float)minimumActionHeight;
- (int)permittedActionLayoutDirection;
- (id)preferredActionFont;
- (id)regularActionFont;
- (struct UIEdgeInsets { float x1; float x2; float x3; float x4; })textFieldCollectionViewContentInset;
- (id)textFieldContainingViewWithTextField:(id)arg1;
- (float)textFieldHorizontalMargin;
- (id)titleLabelColor;
- (id)titleLabelFont;

@end
