/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIApplicationRotationFollowingControllerNoTouches : UIApplicationRotationFollowingController

- (void)loadView;

// UIApplicationRotationFollowingControllerNoTouches (UIInputWindowControllerCompatibility)

- (void)_finishRotationFromInterfaceOrientation:(int)arg1;
- (void)_prepareForRotationToOrientation:(int)arg1 duration:(float)arg2;
- (void)_rotateToOrientation:(int)arg1 duration:(float)arg2;

@end
