/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UICollectionViewControllerWrapperView : UIView

- (id)_collectionViewController;
- (id)_viewControllerToNotifyOnLayoutSubviews;
- (void)didMoveToSuperview;
- (id)preferredFocusedItem;

@end
