/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIDevice : NSObject {
    float  _batteryLevel;
    struct { 
        unsigned int batteryMonitoringEnabled : 1; 
        unsigned int proximityMonitoringEnabled : 1; 
        unsigned int expectsFaceContactInLandscape : 1; 
        unsigned int orientation : 3; 
        unsigned int batteryState : 2; 
        unsigned int proximityState : 1; 
        unsigned int hasTouchPadOverride : 1; 
        unsigned int hasTouchPad : 1; 
    }  _deviceFlags;
    int  _numDeviceOrientationObservers;
}

@property (setter=_setBacklightLevel:, nonatomic) float _backlightLevel;
@property (nonatomic, readonly) float batteryLevel;
@property (getter=isBatteryMonitoringEnabled, nonatomic) BOOL batteryMonitoringEnabled;
@property (nonatomic, readonly) int batteryState;
@property (nonatomic, readonly, retain) NSString *buildVersion;
@property (getter=isGeneratingDeviceOrientationNotifications, nonatomic, readonly) BOOL generatesDeviceOrientationNotifications;
@property (nonatomic, readonly) NSUUID *identifierForVendor;
@property (nonatomic, readonly) NSString *localizedModel;
@property (nonatomic, readonly) NSString *model;
@property (getter=isMultitaskingSupported, nonatomic, readonly) BOOL multitaskingSupported;
@property (nonatomic, readonly) NSString *name;
@property (nonatomic) int orientation;
@property (nonatomic, readonly) int orientation;
@property (getter=isProximityMonitoringEnabled, nonatomic) BOOL proximityMonitoringEnabled;
@property (nonatomic, readonly) BOOL proximityState;
@property (nonatomic, readonly) NSString *systemName;
@property (nonatomic, readonly) NSString *systemVersion;
@property (nonatomic, readonly) int userInterfaceIdiom;

+ (BOOL)_isWatch;
+ (BOOL)_isWatchCompanion;
+ (id)currentDevice;
+ (int)currentDeviceOrientationAllowingAmbiguous:(BOOL)arg1;

- (float)_backlightLevel;
- (id)_deviceInfoForKey:(struct __CFString { }*)arg1;
- (BOOL)_isSystemSoundEnabled;
- (void)_playInputDeleteSound;
- (void)_playInputSelectSound;
- (void)_playSystemSound:(unsigned long)arg1;
- (void)_registerForSystemSounds:(id)arg1;
- (void)_setActiveUserInterfaceIdiom:(int)arg1;
- (void)_setBacklightLevel:(float)arg1;
- (void)_setExpectsFaceContactInLandscape:(BOOL)arg1;
- (float)_softwareDimmingAlpha;
- (void)_unregisterForSystemSounds:(id)arg1;
- (void)_updateSystemSoundActiveStatus:(id)arg1;
- (float)batteryLevel;
- (int)batteryState;
- (void)beginGeneratingDeviceOrientationNotifications;
- (id)buildVersion;
- (void)endGeneratingDeviceOrientationNotifications;
- (id)identifierForVendor;
- (BOOL)isBatteryMonitoringEnabled;
- (BOOL)isGeneratingDeviceOrientationNotifications;
- (BOOL)isMultitaskingSupported;
- (BOOL)isProximityMonitoringEnabled;
- (id)localizedModel;
- (id)model;
- (id)name;
- (int)orientation;
- (void)playInputClick;
- (BOOL)proximityState;
- (void)setBatteryMonitoringEnabled:(BOOL)arg1;
- (void)setOrientation:(int)arg1;
- (void)setOrientation:(int)arg1 animated:(BOOL)arg2;
- (void)setProximityMonitoringEnabled:(BOOL)arg1;
- (id)systemName;
- (id)systemVersion;
- (id)uniqueIdentifier;
- (int)userInterfaceIdiom;

// UIDevice (Private)

- (void)_enableDeviceOrientationEvents:(BOOL)arg1;

// UIDevice (UIDeviceInternal)

+ (BOOL)_isLowEnd;

- (int)_keyboardGraphicsQuality;
- (int)_predictionGraphicsQuality;

// UIDevice (UIDevicePrivate)

+ (id)modelSpecificLocalizedStringKeyForKey:(id)arg1;

- (void)_clearGraphicsQualityOverride;
- (int)_graphicsQuality;
- (BOOL)_hasGraphicsQualityOverride;
- (BOOL)_hasTouchPad;
- (BOOL)_isTTYEnabled;
- (void)_setBatteryLevel:(float)arg1;
- (void)_setBatteryState:(int)arg1;
- (void)_setGraphicsQualityOverride:(int)arg1;
- (void)_setHasTouchPad:(BOOL)arg1;
- (void)_setProximityState:(BOOL)arg1;

@end
