/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIDelayedControlTargetAction : UIControlTargetAction {
    UIEvent * _event;
}

@property (nonatomic, retain) UIEvent *event;

- (void).cxx_destruct;
- (id)event;
- (void)setEvent:(id)arg1;

@end
