/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIDebuggingInformationValueViewNumber : UIDebuggingInformationValueView

- (void)_sliderValueChanged:(id)arg1;
- (void)addViewsToContentView;

@end
