/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIDebuggingInformationValueTableViewCell : UITableViewCell {
    UIView * _valueView;
}

@property (nonatomic, retain) UIView *valueView;

- (void).cxx_destruct;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)setValueView:(id)arg1;
- (id)valueView;

@end
