/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIDOMHTMLOptGroupSelectedItem : NSObject <UIWebSelectedItemPrivate> {
    DOMHTMLOptGroupElement * _node;
}

@property (nonatomic, retain) DOMHTMLOptGroupElement *_node;

- (id)_node;
- (void)dealloc;
- (id)initWithHTMLOptGroupNode:(id)arg1;
- (BOOL)isGroup;
- (id)node;
- (BOOL)selected;
- (void)setSelected:(BOOL)arg1;
- (void)set_node:(id)arg1;
- (void)unselect;

@end
