/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIFetchContentInBackgroundActionResponse : BSActionResponse

@property (nonatomic, readonly) unsigned int result;

+ (id)responseWithResult:(unsigned int)arg1;

- (id)initWithBackgroundFetchResult:(unsigned int)arg1;
- (id)initWithInfo:(id)arg1 error:(id)arg2;
- (id)keyDescriptionForSetting:(unsigned int)arg1;
- (unsigned int)result;

@end
