/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIImageNibPlaceholder : UIImage <NSCoding> {
    NSString * runtimeResourceName;
}

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithContentsOfFile:(id)arg1 andRuntimeResourceName:(id)arg2;
- (id)initWithData:(id)arg1 andRuntimeResourceName:(id)arg2;

@end
