/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIInputViewSetPlacementOnScreen : UIInputViewSetPlacement <NSSecureCoding>

+ (BOOL)supportsSecureCoding;

- (BOOL)inputViewWillAppear;
- (BOOL)showsInputViews;
- (BOOL)showsKeyboard;

@end
