/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKBRenderFactoryiPadLandscapePasscode : UIKBRenderFactoryiPadLandscape

- (id)_traitsForKey:(id)arg1 onKeyplane:(id)arg2;
- (id)activeControlKeyTraits;
- (id)backgroundTraitsForKeyplane:(id)arg1;
- (id)controlKeyTraits;
- (id)defaultKeyBackgroundColorName;
- (id)hashStringElement;
- (float)passcodeEdgeWeight;
- (id)shiftLockControlKeyTraits;

@end
