/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKBEmojiSnapshotSizingView : UIView {
    struct CGSize { 
        float width; 
        float height; 
    }  _snapshotSize;
    UIView * _snapshotView;
}

@property (nonatomic, readonly) UIView *snapshotView;

- (void)dealloc;
- (id)initWithSnapshotView:(id)arg1;
- (void)layoutSubviews;
- (id)snapshotView;

@end
