/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKBRenderFactoryEmoji_iPhone : UIKBRenderFactory_Emoji

- (id)_traitsForKey:(id)arg1 onKeyplane:(id)arg2;
- (struct CGPoint { float x1; float x2; })emojiInternationalKeyOffset;
- (float)emojiInternationalKeySize;
- (struct CGPoint { float x1; float x2; })emojiPopupTextOffset;
- (BOOL)shouldClearBaseDisplayStringForVariants:(id)arg1;
- (id)traitsHashStringForKey:(id)arg1 withGeometry:(id)arg2 controlOpacities:(BOOL)arg3;

@end
