/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKBRenderFactoryHWR_Landscape : UIKBRenderFactoryHWR_Portrait

- (struct CGPoint { float x1; float x2; })deleteGlyphOffset;
- (struct UIEdgeInsets { float x1; float x2; float x3; float x4; })handwritingAreaInsets;
- (float)handwritingGradientStartLocation;
- (void)setupLayoutSegments;
- (float)spaceKeyFontSize;
- (struct CGPoint { float x1; float x2; })spaceKeyTextOffset;

@end
