/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKBRenderFactory50On_Portrait : UIKBRenderFactory10Key

- (void)_customizeTraits:(id)arg1 forPopupForKey:(id)arg2 withRenderConfig:(id)arg3 keycapsFontName:(id)arg4;
- (id)_traitsForKey:(id)arg1 onKeyplane:(id)arg2;
- (float)controlColumnWidthFactor;
- (float)deleteKeyFontSize;
- (float)keyCornerRadius;
- (float)keyplaneSwitchKeyFontSize;
- (id)lightKeycapsFontName;
- (float)returnKeyFontSize;
- (void)setupLayoutSegments;
- (float)spaceKeyFontSize;
- (id)thinKeycapsFontName;

@end
