/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKBRenderFactoryiPad10Key_Landscape : UIKBRenderFactoryiPad10Key_Portrait

- (float)controlColumnWidthFactor;
- (float)keyCornerRadius;
- (id)multitapCompleteKeyImageName;
- (id)muttitapReverseKeyImageName;

@end
