/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKBRenderFactory_CarLinear : UIKBRenderFactory_Car

- (id)_traitsForKey:(id)arg1 onKeyplane:(id)arg2;
- (float)activeLetterFontSize;
- (float)carKeyRadius;
- (float)defaultKeyFontSize;
- (float)letterLineFontSize;
- (id)lightTextFontName;
- (void)setupLayoutSegments;

@end
