/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKBRenderFactory10Key_LandscapeTruffle : UIKBRenderFactory10Key_Landscape

- (float)controlColumnWidthFactor;
- (void)setupColumnLayoutSegmentsWithControlWidth:(float)arg1;

@end
