/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKeyboardBehaviors_Handwriting : TIKeyboardBehaviors {
    BOOL  _usesCandidateSelection;
}

@property (nonatomic) BOOL usesCandidateSelection;

- (id)keyBehaviorsForState:(id)arg1;
- (void)setUsesCandidateSelection:(BOOL)arg1;
- (BOOL)usesCandidateSelection;

@end
