/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKeyboardCandidateGridHeaderContainerView : UICollectionReusableView

+ (id)collectionViewKind;
+ (id)reuseIdentifier;

- (void)setHeaderView:(id)arg1;

@end
