/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKeyCommandDiscoverabilityHUDVisualStyleCompact : UIKeyCommandDiscoverabilityHUDVisualStyleRegular {
    UIFont * _summaryFont;
}

- (void).cxx_destruct;
- (float)HUDPageControlBottomMargin;
- (struct UIEdgeInsets { float x1; float x2; float x3; float x4; })HUDViewInsets;
- (float)maxHUDWidthForWidth:(float)arg1;
- (float)summaryDescriptionToModifiersSpacing;
- (id)summaryFont;
- (float)summaryXPadding;

@end
