/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIKeyboardSliceStore : NSObject {
    NSMutableDictionary * _store;
}

+ (void)archiveSet:(id)arg1;
+ (id)sharedStore;
+ (id)sliceSetForID:(id)arg1;
+ (id)sliceSetIDForKeyplaneName:(id)arg1 type:(int)arg2 orientation:(int)arg3;

- (void).cxx_destruct;
- (void)addSet:(id)arg1;
- (id)init;
- (id)sliceSetForID:(id)arg1;

@end
