/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UILexicon : NSObject <NSCopying> {
    NSArray * _entries;
}

@property (nonatomic, readonly) NSArray *entries;

+ (id)_lexiconWithTILexicon:(id)arg1;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)entries;
- (BOOL)isEqual:(id)arg1;

@end
