/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIMovieScrubberThumbnailView : UIImageView {
    unsigned int  _hasPlaceholderImage;
}

- (BOOL)hasPlaceholderImage;
- (void)setHasPlaceholderImage:(BOOL)arg1;

@end
