/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIMoreListCellLayoutManager : UITableViewCellLayoutManager {
    float  _widestImageWidth;
}

- (void)layoutSubviewsOfCell:(id)arg1;
- (float)setWidestImageWidthFromViewControllers:(id)arg1;

@end
