/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIMutableUserNotificationAction : UIUserNotificationAction

@property (nonatomic) unsigned int activationMode;
@property (getter=isAuthenticationRequired, nonatomic) BOOL authenticationRequired;
@property (nonatomic) unsigned int behavior;
@property (getter=isDestructive, nonatomic) BOOL destructive;
@property (nonatomic, copy) NSString *identifier;
@property (nonatomic, copy) NSDictionary *parameters;
@property (nonatomic, copy) NSString *title;

- (id)copyWithZone:(struct _NSZone { }*)arg1;

@end
