/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIPanGestureVelocitySample : NSObject {
    double  dt;
    struct CGPoint { 
        float x; 
        float y; 
    }  end;
    struct CGPoint { 
        float x; 
        float y; 
    }  start;
}

@property double dt;
@property struct CGPoint { float x1; float x2; } end;
@property struct CGPoint { float x1; float x2; } start;

- (double)dt;
- (struct CGPoint { float x1; float x2; })end;
- (void)setDt:(double)arg1;
- (void)setEnd:(struct CGPoint { float x1; float x2; })arg1;
- (void)setStart:(struct CGPoint { float x1; float x2; })arg1;
- (struct CGPoint { float x1; float x2; })start;

@end
