/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIPasteboard : NSObject {
    NSString * _name;
}

@property (nonatomic, copy) NSURL *URL;
@property (nonatomic, copy) NSArray *URLs;
@property (nonatomic, readonly) int changeCount;
@property (nonatomic, copy) UIColor *color;
@property (nonatomic, copy) NSArray *colors;
@property (nonatomic, copy) UIImage *image;
@property (nonatomic, copy) NSArray *images;
@property (nonatomic, copy) NSArray *items;
@property (nonatomic, readonly) NSString *name;
@property (nonatomic, readonly) int numberOfItems;
@property (getter=isPersistent, nonatomic) BOOL persistent;
@property (nonatomic, copy) NSString *string;
@property (nonatomic, copy) NSArray *strings;

+ (id)generalPasteboard;
+ (id)pasteboardWithName:(id)arg1 create:(BOOL)arg2;
+ (id)pasteboardWithUniqueName;
+ (void)removePasteboardWithName:(id)arg1;

- (void)_addItems:(id)arg1 oldPasteboardTypes:(id)arg2;
- (void)addItems:(id)arg1;
- (int)changeCount;
- (BOOL)containsPasteboardTypes:(id)arg1;
- (BOOL)containsPasteboardTypes:(id)arg1 inItemSet:(id)arg2;
- (id)dataForPasteboardType:(id)arg1;
- (id)dataForPasteboardType:(id)arg1 inItemSet:(id)arg2;
- (void)dealloc;
- (id)init;
- (BOOL)isPersistent;
- (id)itemSetWithPasteboardTypes:(id)arg1;
- (id)items;
- (id)name;
- (int)numberOfItems;
- (id)pasteboardTypes;
- (id)pasteboardTypesForItemSet:(id)arg1;
- (void)setData:(id)arg1 forPasteboardType:(id)arg2;
- (void)setItems:(id)arg1;
- (void)setPersistent:(BOOL)arg1;
- (void)setValue:(id)arg1 forPasteboardType:(id)arg2;
- (id)valueForPasteboardType:(id)arg1;
- (id)valuesForPasteboardType:(id)arg1 inItemSet:(id)arg2;

// UIPasteboard (Static)

+ (id)_findPasteboard;
+ (id)_printPasteboard;

- (id)_initWithName:(id)arg1 system:(BOOL)arg2 create:(BOOL)arg3;
- (void)_pasteboardChanged:(id)arg1;

// UIPasteboard (UIPasteboardDataExtensions)

- (id)URL;
- (id)URLs;
- (id)color;
- (id)colors;
- (id)image;
- (id)images;
- (void)setColor:(id)arg1;
- (void)setColors:(id)arg1;
- (void)setImage:(id)arg1;
- (void)setImages:(id)arg1;
- (void)setString:(id)arg1;
- (void)setStrings:(id)arg1;
- (void)setURL:(id)arg1;
- (void)setURLs:(id)arg1;
- (id)string;
- (id)strings;

@end
