/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIPickerTableViewCell : UITableViewCell {
    UITapGestureRecognizer * _tap;
    UIPickerTableView * pickerTable;
}

@property (nonatomic) UIPickerTableView *pickerTable;

- (void).cxx_destruct;
- (void)_setIsCenterCell:(BOOL)arg1 shouldModifyAlphaOfView:(BOOL)arg2;
- (void)_tapAction:(id)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (id)pickerTable;
- (void)setPickerTable:(id)arg1;

@end
