/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIPPTRequestAction : BSAction

- (int)UIActionType;
- (id)initWithDesiredOrientation:(int)arg1;
- (int)orientationRequested;
- (BOOL)shouldChangeOrientation;

@end
