/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIPrintingMessageView : UIView {
    UILabel * _message;
    UILabel * _title;
}

- (void).cxx_destruct;
- (id)initInView:(id)arg1 title:(id)arg2;
- (void)setMessage:(id)arg1;

@end
