/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIPrintActivityWrapperNavigationController : UINavigationController {
    id /* block */  _completionHandler;
    BOOL  _presentedPrintInteractionController;
}

@property (nonatomic) BOOL presentedPrintInteractionController;

- (void).cxx_destruct;
- (id)initWithCompletion:(id /* block */)arg1;
- (BOOL)presentedPrintInteractionController;
- (void)setPresentedPrintInteractionController:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;

@end
