/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIProgressIndicator : UIActivityIndicatorView

@property (nonatomic) int progressIndicatorStyle;

+ (struct CGSize { float x1; float x2; })size;

- (int)progressIndicatorStyle;
- (void)setAnimating:(BOOL)arg1;
- (void)setProgressIndicatorStyle:(int)arg1;
- (void)setStyle:(int)arg1;
- (void)startAnimation;
- (void)stopAnimation;

@end
