/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIPrinterSetupDisplayPINView : UIView {
    UIButton * _nextButton;
    UILabel * _titleLabel;
}

@property (nonatomic, retain) UIButton *nextButton;
@property (nonatomic, retain) UILabel *titleLabel;

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (void)layoutSubviews;
- (id)nextButton;
- (void)setMessage:(id)arg1 showButton:(BOOL)arg2;
- (void)setNextButton:(id)arg1;
- (void)setTitleLabel:(id)arg1;
- (id)titleLabel;

@end
