/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIPrinterTableViewCell : UITableViewCell {
    UIView * _additionalAccessoryView;
    int  _printerState;
}

@property (nonatomic, retain) UIView *additionalAccessoryView;
@property (nonatomic) int printerState;

- (void).cxx_destruct;
- (id)additionalAccessoryView;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (int)printerState;
- (void)setAdditionalAccessoryView:(id)arg1;
- (void)setPrinterState:(int)arg1;

@end
