/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIRemoteControlEvent : UIEvent {
    int  _subtype;
}

- (id)_init;
- (void)_sendEventToResponder:(id)arg1;
- (void)_setSubtype:(int)arg1;
- (void)_simpleRemoteActionNotification:(id)arg1;
- (id)_windows;
- (void)dealloc;
- (int)subtype;
- (int)type;

@end
