/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UISegmentLabel : UILabel {
    UILabel * _associatedLabel;
}

@property (nonatomic) UILabel *associatedLabel;

- (void).cxx_destruct;
- (id)_associatedScalingLabel;
- (id)_disabledFontColor;
- (id)_parentSegment;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (id)associatedLabel;
- (id)init;
- (void)setAssociatedLabel:(id)arg1;

@end
