/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UISelectionTapRecognizer : UITextTapRecognizer {
    UIResponder<UITextInput> * _textView;
}

@property UIResponder<UITextInput> *textView;

- (BOOL)isCloseToSelection;
- (void)setState:(int)arg1;
- (void)setTextView:(id)arg1;
- (id)textView;

@end
