/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UISimpleTextPrintFormatter : UIPrintFormatter

@property (nonatomic, copy) NSAttributedString *attributedText;
@property (nonatomic, retain) UIColor *color;
@property (nonatomic, retain) UIFont *font;
@property (nonatomic, copy) NSString *text;
@property (nonatomic) int textAlignment;

- (id)initWithAttributedText:(id)arg1;
- (id)initWithText:(id)arg1;

@end
