/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarBluetoothItemView : UIStatusBarItemView {
    BOOL  _connected;
    BOOL  _shouldAnimateConnection;
}

- (void)_blinkAnimationDidStop:(id)arg1 finished:(id)arg2 context:(id)arg3;
- (float)alphaForConnected:(BOOL)arg1;
- (id)contentsImage;
- (void)performPendedActions;
- (void)setVisible:(BOOL)arg1;
- (BOOL)updateForNewData:(id)arg1 actions:(int)arg2;

@end
