/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarBluetoothBatteryItemView : UIStatusBarItemView {
    int  _capacity;
}

- (id)contentsImage;
- (float)extraLeftPadding;
- (BOOL)updateForNewData:(id)arg1 actions:(int)arg2;

@end
