/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarDataNetworkItemView : UIStatusBarItemView {
    int  _dataNetworkType;
    BOOL  _enableRSSI;
    BOOL  _showRSSI;
    int  _wifiStrengthBars;
    int  _wifiStrengthRaw;
}

- (id)_dataNetworkImage;
- (id)_stringForRSSI;
- (id)contentsImage;
- (float)extraLeftPadding;
- (float)maximumOverlap;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (BOOL)updateForNewData:(id)arg1 actions:(int)arg2;

@end
