/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarOrientationAnimationParameters : UIStatusBarAnimationParameters {
    int  _orientationAnimation;
}

@property (nonatomic) int orientationAnimation;

- (id)initWithDefaultParameters;
- (int)orientationAnimation;
- (void)setOrientationAnimation:(int)arg1;
- (BOOL)shouldAnimate;

@end
