/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarRadarItemView : UIStatusBarButtonActionItemView

- (int)buttonType;
- (id)contentsImage;
- (float)extraRightPadding;

@end
