/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarThermalColorItemView : UIStatusBarItemView {
    BOOL  _sunlightMode;
    int  _thermalColor;
}

- (id)_color;
- (id)contentsImage;
- (BOOL)updateForNewData:(id)arg1 actions:(int)arg2;

@end
