/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStoryboardScene : NSObject {
    UIViewController * sceneViewController;
}

@property (nonatomic, retain) UIViewController *sceneViewController;

- (void)dealloc;
- (id)sceneViewController;
- (void)setSceneViewController:(id)arg1;

@end
