/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIStatusBarBatteryPercentItemView : UIStatusBarItemView {
    NSString * _percentString;
}

- (void).cxx_destruct;
- (BOOL)animatesDataChange;
- (id)contentsImage;
- (float)extraRightPadding;
- (int)textAlignment;
- (int)textStyle;
- (BOOL)updateForNewData:(id)arg1 actions:(int)arg2;

@end
