/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UISubTest : NSObject {
    NSMutableArray * _fps;
    BOOL  _showFps;
    BOOL  _showTime;
    NSNumber * _startFrame;
    NSNumber * _startTime;
    NSString * _testName;
    NSMutableArray * _time;
}

- (void).cxx_destruct;
- (id)initWithName:(id)arg1 metrics:(id)arg2;
- (id)outputData;
- (void)startWithFrameCount:(id)arg1;
- (void)stopWithFrameCount:(id)arg1;

@end
