/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UISystemNavigationAction : BSAction

@property (nonatomic, readonly, copy) NSString *applicationName;

- (int)UIActionType;
- (id)applicationName;
- (id)generateApplicationIcon;
- (id)initWithApplicationName:(id)arg1 andIconData:(id)arg2 withScale:(float)arg3 forResponseOnQueue:(id)arg4 withHandler:(id /* block */)arg5;
- (id)initWithInfo:(id)arg1 timeout:(double)arg2 forResponseOnQueue:(id)arg3 withHandler:(id /* block */)arg4;
- (id)keyDescriptionForSetting:(unsigned int)arg1;

@end
