/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UITableViewLabel : UILabel {
    UITableViewCell * _tableCell;
}

@property (nonatomic) UITableViewCell *tableCell;

- (void).cxx_destruct;
- (void)setTableCell:(id)arg1;
- (void)setText:(id)arg1;
- (id)tableCell;

@end
