/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UITableViewIndexOverlayIndicatorView : UIView {
    UILabel * _label;
    UITableView * _table;
    UITapGestureRecognizer * _tapGestureRecognizer;
}

@property (nonatomic, copy) NSString *currentText;

- (void).cxx_destruct;
- (void)_invalidateTable;
- (void)_tapGestureChanged:(id)arg1;
- (void)_willChangeToIdiom:(int)arg1 onScreen:(id)arg2;
- (id)currentText;
- (id)initWithTable:(id)arg1;
- (void)layoutSubviews;
- (void)setCurrentText:(id)arg1;

@end
