/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UITextInputAssistantItem : NSObject {
    NSArray * _leadingBarButtonGroups;
    UIKeyboardAssistantBar * _owner;
    NSArray * _trailingBarButtonGroups;
}

@property (nonatomic, copy) NSArray *leadingBarButtonGroups;
@property (getter=_owner, setter=_setOwner:, nonatomic) UIKeyboardAssistantBar *owner;
@property (nonatomic, copy) NSArray *trailingBarButtonGroups;

- (id)_owner;
- (void)_setOwner:(id)arg1;
- (void)dealloc;
- (id)description;
- (id)leadingBarButtonGroups;
- (void)setLeadingBarButtonGroups:(id)arg1;
- (void)setTrailingBarButtonGroups:(id)arg1;
- (id)trailingBarButtonGroups;

@end
