/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UITextEffectsWindow : UIAutoRotatingWindow <_UIScreenBasedObject> {
    unsigned int  _activeEffectsCount;
    unsigned int  _activeRemoteViewCount;
    float  _defaultWindowLevel;
    struct CGSize { 
        float width; 
        float height; 
    }  _hostedSceneSize;
    struct CGPoint { 
        float x; 
        float y; 
    }  _hostedWindowOffset;
    BOOL  _inDealloc;
    NSDictionary * _perScreenOptions;
    unsigned int  _windowLevelCount;
    float  _windowLevelStack;
}

@property (readonly) UIScreen *_intendedScreen;
@property (readonly) NSDictionary *_options;
@property (readonly) unsigned int contextID;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) float defaultWindowLevel;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned int hash;
@property (nonatomic, readonly) struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; } hostedFrame;
@property (nonatomic) struct CGSize { float x1; float x2; } hostedSceneSize;
@property (nonatomic) struct CGPoint { float x1; float x2; } hostedWindowOffset;
@property (readonly) Class superclass;

+ (id)_sharedTextEffectsWindowforScreen:(id)arg1 aboveStatusBar:(BOOL)arg2 allowHosted:(BOOL)arg3 matchesStatusBarOrientationOnAccess:(BOOL)arg4;
+ (id)activeTextEffectsWindowForScreen:(id)arg1;
+ (void)lowerTextEffectsWindowsForHideNotificationCenter;
+ (void)raiseTextEffectsWindowsForShowNotificationCenter;
+ (void)releaseSharedInstances;
+ (id)sharedTextEffectsWindow;
+ (id)sharedTextEffectsWindowAboveStatusBar;
+ (id)sharedTextEffectsWindowForScreen:(id)arg1;

- (void).cxx_destruct;
- (struct CGPoint { float x1; float x2; })_adjustPointForHostedDisplay:(struct CGPoint { float x1; float x2; })arg1 hasTarget:(BOOL)arg2 inset:(BOOL)arg3;
- (BOOL)_canActAsKeyWindowForScreen:(id)arg1;
- (BOOL)_canAffectStatusBarAppearance;
- (void)_commonTextEffectsInit;
- (void)_configureContextOptions:(id)arg1;
- (void)_createSystemGestureGateGestureRecognizerIfNeeded;
- (void)_didRemoveSubview:(id)arg1;
- (id)_initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1 attached:(BOOL)arg2;
- (BOOL)_isFullscreen;
- (BOOL)_isTextEffectsWindow;
- (void)_matchDeviceOrientation;
- (void)_restoreWindowLevel;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })_sceneBounds;
- (void)_sceneBoundsDidChange;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })_sceneReferenceBounds;
- (void)_setWindowLevel:(float)arg1;
- (BOOL)_shouldParticipateInVirtualResizing;
- (BOOL)_shouldResizeWithScene;
- (BOOL)_shouldTintStatusBar;
- (void)_updateTransformLayer;
- (void)_updateTransformLayerForClassicPresentation;
- (id)aboveStatusBarWindow;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })actualSceneBounds;
- (void)bringSubviewToFront:(id)arg1;
- (struct CGPoint { float x1; float x2; })classicWindowPointForPoint:(struct CGPoint { float x1; float x2; })arg1;
- (unsigned int)contextID;
- (struct CGPoint { float x1; float x2; })convertPoint:(struct CGPoint { float x1; float x2; })arg1 fromView:(id)arg2;
- (struct CGPoint { float x1; float x2; })convertPoint:(struct CGPoint { float x1; float x2; })arg1 fromWindow:(id)arg2;
- (struct CGPoint { float x1; float x2; })convertPoint:(struct CGPoint { float x1; float x2; })arg1 toView:(id)arg2;
- (struct CGPoint { float x1; float x2; })convertPoint:(struct CGPoint { float x1; float x2; })arg1 toWindow:(id)arg2;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })convertRect:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1 fromView:(id)arg2;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })convertRect:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1 fromWindow:(id)arg2;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })convertRect:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1 toView:(id)arg2;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })convertRect:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1 toWindow:(id)arg2;
- (void)dealloc;
- (float)defaultWindowLevel;
- (void)delayHideWindow;
- (void)didAddSubview:(id)arg1;
- (void)handleStatusBarChangeFromHeight:(float)arg1 toHeight:(float)arg2;
- (struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })hostedFrame;
- (struct CGSize { float x1; float x2; })hostedSceneSize;
- (struct CGPoint { float x1; float x2; })hostedWindowOffset;
- (id)initWithFrame:(struct CGRect { struct CGPoint { float x_1_1_1; float x_1_1_2; } x1; struct CGSize { float x_2_1_1; float x_2_1_2; } x2; })arg1;
- (int)interfaceOrientation;
- (BOOL)isInternalWindow;
- (struct CGPoint { float x1; float x2; })magnifierScreenPointForPoint:(struct CGPoint { float x1; float x2; })arg1 targetWindow:(id)arg2;
- (void)resetTransform;
- (void)sendSubviewToBack:(id)arg1;
- (void)setDefaultWindowLevel:(float)arg1;
- (void)setHostedSceneSize:(struct CGSize { float x1; float x2; })arg1;
- (void)setHostedWindowOffset:(struct CGPoint { float x1; float x2; })arg1;
- (void)sortSubviews;
- (void)updateForOrientation:(int)arg1;
- (void)updateForOrientation:(int)arg1 forceResetTransform:(BOOL)arg2;
- (void)updateSubviewOrdering;

// UITextEffectsWindow (UIObjectsForPerScreen)

- (id)_initBasicWithScreen:(id)arg1 options:(id)arg2;
- (id)_initWithScreen:(id)arg1 options:(id)arg2;
- (id)_intendedScreen;
- (BOOL)_matchingOptions:(id)arg1;
- (id)_options;

@end
