/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UITextFieldCenteredLabel : UITextFieldLabel {
    float  _textWidth;
    float  _textXPosition;
}

@property (nonatomic) float textWidth;
@property (nonatomic) float textXPosition;

- (BOOL)_isTextFieldCenteredLabel;
- (void)setTextWidth:(float)arg1;
- (void)setTextXPosition:(float)arg1;
- (float)textWidth;
- (float)textXPosition;

@end
