/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIVibrancyEffect : UIVisualEffect {
    int  _blurStyle;
}

+ (id)effectForBlurEffect:(id)arg1;
+ (BOOL)supportsSecureCoding;

- (id)_highQualityEffectConfig;
- (id)_lowQualityEffectConfig;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)effectConfig;
- (id)effectConfigForQuality:(int)arg1;
- (id)effectForUserInterfaceStyle:(int)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end
