/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIWebElementActionInfo : NSObject {
    struct CGPoint { 
        float x; 
        float y; 
    }  _interactionLocation;
}

@property (nonatomic, readonly) struct CGPoint { float x1; float x2; } interactionLocation;

- (void)_setInteractionLocation:(struct CGPoint { float x1; float x2; })arg1;
- (struct CGPoint { float x1; float x2; })interactionLocation;

@end
