/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIWebFormRotatingAccessoryPopover : UIWebRotatingNodePopover <UIWebRotatingNodePopoverDelegate>

- (void)accessoryDone;
- (id)initWithDOMNode:(id)arg1;
- (unsigned int)popoverArrowDirections;
- (void)popoverWasDismissed:(id)arg1;

@end
