/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIWebViewInternal : NSObject {
    UIWebBrowserView * browserView;
    UICheckeredPatternView * checkeredPatternView;
    int  clickedAlertButtonIndex;
    <UIWebViewDelegate> * delegate;
    unsigned int  didRotateEnclosingScrollView;
    unsigned int  drawInWebThread;
    unsigned int  drawsCheckeredPattern;
    unsigned int  hasOverriddenOrientationChangeEventHandling;
    unsigned int  inRotation;
    unsigned int  isLoading;
    UIWebPDFViewHandler * pdfHandler;
    NSURLRequest * request;
    unsigned int  scalesPageToFit;
    UIScrollView * scroller;
    unsigned int  webSelectionEnabled;
    UIWebViewWebViewDelegate * webViewDelegate;
}

@end
