/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface UIWebRotatingAlertController : _UIRotatingAlertController {
    BOOL  _wasDeferringCallbacks;
    UIWebDocumentView * _webBrowserView;
}

- (void).cxx_destruct;
- (void)_disableWebView;
- (void)_enableWebView;
- (void)dealloc;
- (void)doneWithSheet;
- (id)initWithUIWebDocumentView:(id)arg1;
- (BOOL)presentSheet;

@end
