/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/UIKit.framework/UIKit
 */

@interface WebThreadSafeUndoManager : NSUndoManager

- (BOOL)_alwaysShowEditAlertView;
- (void)redo;
- (void)undo;

@end
