/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVAssetDownloadSessionInternal : NSObject {
    NSURL * URL;
    AVURLAsset * asset;
    struct CMBaseObject { } * assetDownloader;
    NSNumber * cachePrimingDownloadTokenNum;
    NSURL * destinationURL;
    unsigned long long  downloadToken;
    NSError * error;
    struct OpaqueFigAsset { } * figAsset;
    struct OpaqueFigPlaybackItem { } * playbackItem;
    struct OpaqueFigPlayer { } * player;
    int  priority;
    NSObject<OS_dispatch_queue> * readWriteQueue;
    int  status;
    AVWeakReference * weakReference;
}

@end
