/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVAssetResourceLoadingContentInformationRequestInternal : NSObject {
    BOOL  byteRangeAccessSupported;
    long long  contentLength;
    NSString * contentType;
    BOOL  diskCachingPermitted;
    NSDate * renewalDate;
}

@end
