/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVAssetWriterInputPassDescription : NSObject {
    AVAssetWriterInputPassDescriptionInternal * _internal;
}

@property (nonatomic, readonly) NSArray *sourceTimeRanges;

- (void)dealloc;
- (id)description;
- (void)finalize;
- (id)init;
- (id)initWithTimeRanges:(id)arg1;
- (id)sourceTimeRanges;

@end
