/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVAssetCache : NSObject {
    AVAssetCacheInternal * _priv;
}

@property (nonatomic, readonly, copy) NSURL *URL;
@property (nonatomic, readonly) long long currentSize;
@property (nonatomic) long long maxEntrySize;
@property (nonatomic) long long maxSize;

+ (id)assetCacheWithURL:(id)arg1;

- (id)URL;
- (id)allKeys;
- (long long)currentSize;
- (void)dealloc;
- (void)finalize;
- (id)initWithURL:(id)arg1;
- (id)lastModifiedDateOfEntryForKey:(id)arg1;
- (long long)maxEntrySize;
- (long long)maxSize;
- (void)removeEntryForKey:(id)arg1;
- (void)setMaxEntrySize:(long long)arg1;
- (void)setMaxSize:(long long)arg1;
- (long long)sizeOfEntryForKey:(id)arg1;

@end
