/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVCaptureCoreMotionMetadataInput : AVCaptureInput {
    AVCaptureCoreMotionMetadataInputInternal * _internal;
}

@property (nonatomic, readonly) NSString *sourceID;

+ (id)coreMotionMetadataInput;
+ (void)initialize;

- (struct OpaqueCMClock { }*)clock;
- (void)dealloc;
- (id)init;
- (id)ports;
- (id)sourceID;

@end
