/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVCaptureMovieFileOutputInternal : NSObject {
    NSMutableArray * connectionsThatRecordVideoOrientationAndMirroringChangesAsMetadataTrack;
    NSArray * metadata;
    struct { 
        long long value; 
        int timescale; 
        unsigned int flags; 
        long long epoch; 
    }  movieFragmentInterval;
    BOOL  paused;
    BOOL  recording;
    NSMutableArray * recordingDelegatesArray;
    BOOL  sendLastVideoPreviewFrame;
    AVWeakReference * weakReference;
}

- (void)dealloc;
- (id)init;

@end
