/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVCaptureOutputInternal : NSObject {
    int  changeSeed;
    NSMutableArray * connections;
    struct OpaqueFigCaptureSession { } * figCaptureSession;
    NSObject<OS_dispatch_queue> * figCaptureSessionSyncQueue;
    struct CGAffineTransform { 
        float a; 
        float b; 
        float c; 
        float d; 
        float tx; 
        float ty; 
    }  metadataTransform;
    BOOL  physicallyMirrorsVideo;
    float  rollAdjustment;
    AVCaptureSession * session;
    NSString * sinkID;
}

- (void)dealloc;
- (id)init;

@end
