/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVChapterMetadataItemInternal : NSObject {
    NSString * chapterDataType;
    long  chapterGroupIndex;
    long  chapterIndex;
    NSString * chapterType;
    NSMutableArray * completions;
    struct { 
        long long value; 
        int timescale; 
        unsigned int flags; 
        long long epoch; 
    }  duration;
    struct OpaqueFigAsset { } * figAsset;
    NSLocale * locale;
    NSObject<OS_dispatch_queue> * readWriteQueue;
    struct { 
        long long value; 
        int timescale; 
        unsigned int flags; 
        long long epoch; 
    }  time;
    <NSObject><NSCopying> * value;
    long  valueErrorCode;
    int  valueStatus;
    AVWeakReference * weakReference;
}

@end
