/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVFlashlightInternal : NSObject {
    BOOL  available;
    struct OpaqueFigFlashlight { } * flashlight;
    float  flashlightLevel;
    struct OpaqueFigSimpleMutex { } * lock;
    BOOL  overheated;
    AVWeakReference * weakReference;
}

@end
