/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVMetadataItemValueRequest : NSObject {
    AVMetadataItemValueRequestInternal * _valueRequest;
}

@property (readonly) AVMetadataItem *metadataItem;

+ (id)metadataItemValueRequestWithMetadataItem:(id)arg1;

- (void)dealloc;
- (id)error;
- (void)finalize;
- (id)initWithMetadataItem:(id)arg1;
- (id)metadataItem;
- (void)respondWithError:(id)arg1;
- (void)respondWithValue:(id)arg1;
- (id)value;

@end
