/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVMediaSelectionInternal : NSObject {
    AVWeakReference * assetWeakReference;
    NSArray * groupDictionaries;
    NSMutableArray * selectedMediaArray;
}

@end
