/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVOutputContext : NSObject <NSSecureCoding> {
    AVOutputContextInternal * _outputContext;
}

@property (nonatomic, readonly) NSString *deviceName;

+ (id)outputContext;
+ (id)sharedSystemAudioContext;
+ (id)sharedSystemScreenContext;
+ (BOOL)supportsSecureCoding;

- (void)_addFigEndpointPickerNotifications;
- (long)_configureFigEndpointPickerWithFeature:(unsigned int)arg1 options:(id)arg2;
- (void)_removeFigEndpointPickerNotifications;
- (id)_weakReference;
- (int)applicationProcessID;
- (id)contextUUID;
- (void)dealloc;
- (id)deviceName;
- (void)encodeWithCoder:(id)arg1;
- (void)finalize;
- (unsigned int)hash;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithContextUUID:(id)arg1;
- (id)initWithFeature:(unsigned int)arg1 options:(id)arg2;
- (BOOL)isEqual:(id)arg1;
- (id)outputDevice;
- (void)setApplicationProcessID:(int)arg1;
- (BOOL)setOutputDevice:(id)arg1 forFeatures:(unsigned int)arg2;

@end
