/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVOutputDeviceDiscoverySession : NSObject {
    AVOutputDeviceDiscoverySessionInternal * _outputDeviceDiscoverySession;
}

@property (nonatomic, readonly) NSArray *availableOutputDevices;
@property (nonatomic, readonly) AVOutputDeviceDiscoverySessionAvailableOutputDevices *availableOutputDevicesObject;
@property (nonatomic, readonly) BOOL devicePresenceDetected;
@property (nonatomic) int discoveryMode;

- (void)_addFigEndpointPickerNotifications;
- (void)_removeFigEndpointPickerNotifications;
- (id)availableOutputDevices;
- (id)availableOutputDevicesObject;
- (void)dealloc;
- (BOOL)devicePresenceDetected;
- (int)discoveryMode;
- (void)finalize;
- (id)init;
- (id)initWithDeviceFeatures:(unsigned int)arg1;
- (void)setDiscoveryMode:(int)arg1;

@end
