/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVPlayer : NSObject {
    AVPlayerInternal * _player;
}

@property (getter=_isPIPModePossible, nonatomic, readonly) BOOL PIPModePossible;
@property (setter=_setDisplaysUsedForPlayback:, nonatomic, copy) NSArray *_displaysUsedForPlayback;
@property (nonatomic, readonly) int _externalProtectionStatus;
@property (nonatomic) BOOL allowsOutOfBandTextTrackRendering;
@property (nonatomic) BOOL allowsPixelBufferPoolSharing;
@property (nonatomic) BOOL appliesMediaSelectionCriteriaAutomatically;
@property (nonatomic, copy) NSString *audioOutputDeviceUniqueID;
@property (getter=isAudioPlaybackEnabledAtAllRates, nonatomic, readonly) BOOL audioPlaybackEnabledAtAllRates;
@property (getter=_cachedValueForPIPModePossible, nonatomic, readonly) BOOL cachedValueForPIPModePossible;
@property (nonatomic) BOOL disallowsAMRAudio;
@property (nonatomic, readonly) NSError *error;
@property (nonatomic) float maxRateForAudioPlayback;
@property (nonatomic) float minRateForAudioPlayback;
@property (nonatomic, readonly) int status;

+ (BOOL)automaticallyNotifiesObserversOfActionAtItemEnd;
+ (BOOL)automaticallyNotifiesObserversOfAirPlayVideoActive;
+ (BOOL)automaticallyNotifiesObserversOfCurrentItem;
+ (BOOL)automaticallyNotifiesObserversOfExternalPlaybackActive;
+ (BOOL)automaticallyNotifiesObserversOfRate;
+ (BOOL)automaticallyNotifiesObserversOfUserVolume;
+ (BOOL)automaticallyNotifiesObserversOfUsesAirPlayVideoWhileAirPlayScreenIsActive;
+ (BOOL)automaticallyNotifiesObserversOfUsesAudioOnlyModeForExternalPlayback;
+ (BOOL)automaticallyNotifiesObserversOfVibrationPattern;
+ (void)initialize;
+ (id)keyPathsForValuesAffectingActionAtItemEnd;
+ (id)keyPathsForValuesAffectingClosedCaptionDisplayEnabled;
+ (id)keyPathsForValuesAffectingMuted;
+ (id)keyPathsForValuesAffectingRate;
+ (id)keyPathsForValuesAffectingVolume;
+ (id)playerWithPlayerItem:(id)arg1;
+ (id)playerWithURL:(id)arg1;

- (int)_actionAtItemEnd;
- (void)_addFPListeners;
- (void)_addItemToLinkedList_invokeOnIvarAccessQueue:(id)arg1 afterItem:(id)arg2;
- (void)_addLayer:(id)arg1 withPixelBufferAttributes:(id)arg2;
- (void)_advanceCurrentItemAccordingToFigPlaybackItem:(struct OpaqueFigPlaybackItem { }*)arg1;
- (void)_advanceToNextItem;
- (BOOL)_airPlayVideoActive;
- (BOOL)_allowsExternalPlayback;
- (void)_applyNewItemList:(id)arg1 toFigPlayerAfterInsertingItem:(id)arg2 afterItem:(id)arg3;
- (void)_applyNewItemList:(id)arg1 toFigPlayerAfterRemovingItem:(id)arg2;
- (void)_attachClosedCaptionLayersToFigPlayer;
- (void)_attachFigPlayerToSubtitleLayers;
- (void)_attachVideoLayersToFigPlayer;
- (id)_avPlayerLayers;
- (BOOL)_cachedNonForcedSubtitleDisplayEnabledForCurrentItem;
- (struct CGSize { float x1; float x2; })_cachedPresentationSizeOfCurrentItem;
- (id)_cachedValueForKey:(id)arg1;
- (int)_cancelPendingPrerollAndRegisterPrerollCompletionHandler:(id /* block */)arg1;
- (void)_changeStatusToFailedWithError:(id)arg1;
- (id)_closedCaptionLayers;
- (struct OpaqueFigPlayer { }*)_copyFigPlayer;
- (id)_copyPerformanceDataForCurrentItem;
- (void)_createAndConfigureFigPlayerWithType:(int)arg1 completionHandler:(id /* block */)arg2;
- (int)_createPrerollID;
- (int)_defaultActionAtItemEnd;
- (void)_detachClosedCaptionLayersFromFigPlayer;
- (void)_detachFigPlayerFromSubtitleLayers;
- (void)_detachVideoLayersFromFigPlayer;
- (void)_didAccessKVOForKey:(id)arg1;
- (void)_enumerateItemsUsingBlock:(id /* block */)arg1;
- (BOOL)_externalPlaybackActive;
- (id)_fpNotificationNames;
- (void)_grabPropertiesFromNewCurrentItem;
- (void)_insertItem:(id)arg1 afterItem:(id)arg2;
- (BOOL)_insertPlaybackItemOfItem:(id)arg1 inPlayerQueueAfterPlaybackItemOfItem:(id)arg2;
- (BOOL)_isChangingValueForKey:(id)arg1;
- (BOOL)_isClosedCaptionDisplayEnabled;
- (BOOL)_isDisplayingClosedCaptions;
- (BOOL)_isMuted;
- (void)_itemIsReadyToPlay:(id)arg1;
- (id)_items;
- (id)_items_invokeOnIvarAccessQueue;
- (void)_logPerformanceDataForCurrentItem;
- (void)_logPerformanceDataForPreviousItem;
- (void)_noteDisplaySize:(struct CGSize { float x1; float x2; })arg1 forPlayerLayer:(id)arg2;
- (void)_noteNewNonForcedSubtitleDisplayEnabledForPlayerItem:(id)arg1;
- (void)_noteNewPresentationSizeForPlayerItem:(id)arg1;
- (id)_pendingFigPlayerProperties;
- (id)_pendingFigPlayerPropertyForKey:(id)arg1;
- (id)_pixelBufferAttributeMediator;
- (void)_playerLayer:(id)arg1 replaceVideoLayer:(id)arg2 with:(id)arg3;
- (float)_playerVolume;
- (id)_propertyStorage;
- (float)_rate;
- (void)_removeAllItems;
- (void)_removeAllLayers;
- (void)_removeFPListeners;
- (void)_removeItem:(id)arg1;
- (void)_removeItemFromLinkedList_invokeOnIvarAccessQueue:(id)arg1;
- (void)_removeLayer:(id)arg1;
- (void)_runOnIvarAccessQueueOperationThatMayChangeCurrentItemWithPreflightBlock:(id /* block */)arg1 modificationBlock:(id /* block */)arg2;
- (void)_setActionAtItemEnd:(int)arg1 allowingAdvance:(BOOL)arg2;
- (void)_setCachedValue:(id)arg1 forKey:(id)arg2;
- (void)_setCurrentItem:(id)arg1;
- (void)_setFigPlaybackItemToMakeCurrent:(struct OpaqueFigPlaybackItem { }*)arg1;
- (void)_setNeroVideoGravityOnFigPlayer;
- (void)_setPendingFigPlayerProperty:(id)arg1 forKey:(id)arg2;
- (void)_setUserVolume:(float)arg1;
- (BOOL)_shouldLogPerformanceData;
- (BOOL)_shouldReleaseResourcesWhenPaused;
- (void)_startObservingPropertiesOfCurrentItem:(id)arg1;
- (id)_stateDispatchQueue;
- (void)_stopObservingPropertiesOfCurrentItem:(id)arg1;
- (id)_subtitleLayers;
- (id /* block */)_unregisterAndReturnRetainedPrerollCompletionHandler;
- (void)_updateClosedCaptionLayerBounds:(id)arg1;
- (void)_updateCurrentItemPreferredPixelBufferAttributesAndVideoLayerSuppression;
- (void)_updateDecoderPixelBufferAttributes:(id)arg1 onFigPlayer:(struct OpaqueFigPlayer { }*)arg2;
- (void)_updateProxyTimebaseFromNewCurrentItem;
- (float)_userVolume;
- (BOOL)_usesAudioOnlyModeForExternalPlayback;
- (BOOL)_usesExternalPlaybackWhileExternalScreenIsActive;
- (id)_videoLayers;
- (id)_weakReference;
- (void)_willAccessKVOForKey:(id)arg1;
- (int)actionAtItemEnd;
- (id)addBoundaryTimeObserverForTimes:(id)arg1 queue:(id)arg2 usingBlock:(id /* block */)arg3;
- (void)addObserver:(id)arg1 forKeyPath:(id)arg2 options:(unsigned int)arg3 context:(void*)arg4;
- (id)addPeriodicTimeObserverForInterval:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg1 queue:(id)arg2 usingBlock:(id /* block */)arg3;
- (BOOL)allowsAirPlayVideo;
- (BOOL)allowsExternalPlayback;
- (void)cancelPendingPrerolls;
- (id)currentItem;
- (struct { long long x1; int x2; unsigned int x3; long long x4; })currentTime;
- (void)dealloc;
- (void)didChangeValueForKey:(id)arg1;
- (id)dispatchQueue;
- (id)error;
- (id)expectedAssetTypes;
- (int)externalPlaybackType;
- (id)externalPlaybackVideoGravity;
- (void)finalize;
- (id)init;
- (id)initWithDispatchQueue:(id)arg1;
- (id)initWithPlayerItem:(id)arg1;
- (id)initWithURL:(id)arg1;
- (BOOL)isAirPlayVideoActive;
- (BOOL)isClosedCaptionDisplayEnabled;
- (BOOL)isDisplayingClosedCaptions;
- (BOOL)isExternalPlaybackActive;
- (BOOL)isMuted;
- (struct OpaqueCMClock { }*)masterClock;
- (id)outputContext;
- (void)pause;
- (void)play;
- (void)prepareItem:(id)arg1 withCompletionHandler:(id /* block */)arg2;
- (void)prerollAtRate:(float)arg1 completionHandler:(id /* block */)arg2;
- (void)prerollOperationDidComplete:(BOOL)arg1 notificationPayload:(struct __CFDictionary { }*)arg2;
- (float)rate;
- (void)removeTimeObserver:(id)arg1;
- (void)replaceCurrentItemWithPlayerItem:(id)arg1;
- (void)seekToDate:(id)arg1;
- (void)seekToDate:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)seekToTime:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg1;
- (void)seekToTime:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg1 completionHandler:(id /* block */)arg2;
- (void)seekToTime:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg1 toleranceBefore:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg2 toleranceAfter:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg3;
- (void)seekToTime:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg1 toleranceBefore:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg2 toleranceAfter:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg3 completionHandler:(id /* block */)arg4;
- (void)setActionAtItemEnd:(int)arg1;
- (void)setAllowsAirPlayVideo:(BOOL)arg1;
- (void)setAllowsExternalPlayback:(BOOL)arg1;
- (void)setClosedCaptionDisplayEnabled:(BOOL)arg1;
- (void)setExpectedAssetTypes:(id)arg1;
- (void)setExternalPlaybackVideoGravity:(id)arg1;
- (void)setMasterClock:(struct OpaqueCMClock { }*)arg1;
- (void)setMuted:(BOOL)arg1;
- (void)setOutputContext:(id)arg1;
- (void)setRate:(float)arg1;
- (void)setRate:(float)arg1 time:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg2 atHostTime:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg3;
- (void)setRate:(float)arg1 withVolumeRampDuration:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg2;
- (void)setShouldReleaseResourcesWhenPaused:(BOOL)arg1;
- (void)setUsesAirPlayVideoWhileAirPlayScreenIsActive:(BOOL)arg1;
- (void)setUsesAudioOnlyModeForExternalPlayback:(BOOL)arg1;
- (void)setUsesExternalPlaybackWhileExternalScreenIsActive:(BOOL)arg1;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (void)setVibrationPattern:(id)arg1;
- (void)setVolume:(float)arg1;
- (BOOL)shouldReleaseResourcesWhenPaused;
- (int)status;
- (BOOL)usesAirPlayVideoWhileAirPlayScreenIsActive;
- (BOOL)usesAudioOnlyModeForExternalPlayback;
- (BOOL)usesExternalPlaybackWhileExternalScreenIsActive;
- (id)valueForUndefinedKey:(id)arg1;
- (id)vibrationPattern;
- (float)volume;
- (void)willChangeValueForKey:(id)arg1;

// AVPlayer (AVAudioSessionMediaPlayerOnly)

- (id)playerAVAudioSession;

// AVPlayer (AVPlayerAudioDeviceSupport)

+ (BOOL)automaticallyNotifiesObserversOfAutoSwitchStreamVariants;

- (id)_audioOutputDeviceUniqueID;
- (id)audioOutputDeviceUniqueID;
- (BOOL)autoSwitchStreamVariants;
- (BOOL)preparesItemsForPlaybackAsynchronously;
- (void)setAudioOutputDeviceUniqueID:(id)arg1;
- (void)setAutoSwitchStreamVariants:(BOOL)arg1;
- (void)setPreparesItemsForPlaybackAsynchronously:(BOOL)arg1;

// AVPlayer (AVPlayerAudioPlaybackRateLimits)

- (BOOL)isAudioPlaybackEnabledAtAllRates;
- (float)maxRateForAudioPlayback;
- (float)minRateForAudioPlayback;
- (void)removeAudioPlaybackRateLimits;
- (void)setMaxRateForAudioPlayback:(float)arg1;
- (void)setMinRateForAudioPlayback:(float)arg1;

// AVPlayer (AVPlayerAutomaticMediaSelection)

- (BOOL)_appliesMediaSelectionCriteriaAutomatically;
- (BOOL)appliesMediaSelectionCriteriaAutomatically;
- (id)mediaSelectionCriteriaForMediaCharacteristic:(id)arg1;
- (void)setAppliesMediaSelectionCriteriaAutomatically:(BOOL)arg1;
- (void)setMediaSelectionCriteria:(id)arg1 forMediaCharacteristic:(id)arg2;

// AVPlayer (AVPlayerAutomaticMediaSelectionPrivate)

- (id)defaultMediaSelectionCriteriaForMediaCharacteristic:(id)arg1;

// AVPlayer (AVPlayerFormatRestrictions)

- (BOOL)_disallowsAMRAudio;
- (BOOL)_disallowsHardwareAcceleratedVideoDecoder;
- (BOOL)disallowsAMRAudio;
- (BOOL)disallowsHardwareAcceleratedVideoDecoder;
- (void)setDisallowsAMRAudio:(BOOL)arg1;
- (void)setDisallowsHardwareAcceleratedVideoDecoder:(BOOL)arg1;

// AVPlayer (AVPlayerMultitaskSupport)

- (BOOL)_applicationHasExternallyDisplayedAVPlayerLayerAndIsUnderDeviceLock;
- (BOOL)_carplayIsActive;
- (void)_didFinishSuspension:(id)arg1;
- (BOOL)_hasAssociatedAVPlayerLayerInPIPMode;
- (BOOL)_hasAssociatedOnscreenAVPlayerLayer;
- (BOOL)_isIAPDExtendedModeActive;
- (int)_itemOkayToPlayWhileTransitioningToBackground:(id)arg1;
- (BOOL)_shouldDetachVideoLayersFromFigPlayer;
- (void)_willEnterForeground:(id)arg1;

// AVPlayer (AVPlayerOutOfBandTextTrackRendering)

- (BOOL)allowsOutOfBandTextTrackRendering;
- (void)setAllowsOutOfBandTextTrackRendering:(BOOL)arg1;

// AVPlayer (AVPlayerPixelBufferPoolSharing)

- (BOOL)_allowsPixelBufferPoolSharing;
- (BOOL)allowsPixelBufferPoolSharing;
- (void)setAllowsPixelBufferPoolSharing:(BOOL)arg1;

// AVPlayer (AVPlayerProtectedContentPrivate)

- (id)_displaysUsedForPlayback;
- (int)_externalProtectionStatus;
- (int)_extractVerifiedFPExternalProtectionStatus:(id)arg1;
- (BOOL)_outputObscuredDueToInsufficientExternalProtection;
- (id)_playbackDisplaysForFigPlayer;
- (void)_setDisplaysUsedForPlayback:(id)arg1;
- (BOOL)outputObscuredDueToInsufficientExternalProtection;

// AVPlayer (AVPlayerSupportForMediaPlayer)

- (BOOL)_CALayerDestinationIsTVOut;
- (id)_clientName;
- (int)_clientPriority;
- (BOOL)_resumePlayback:(double)arg1 error:(id*)arg2;
- (void)_setCALayerDestinationIsTVOut:(BOOL)arg1;
- (void)_setClientName:(id)arg1;
- (void)_setClientPriority:(int)arg1;
- (void)_setEQPreset:(int)arg1;
- (void)_setPreferredLanguageList:(id)arg1;
- (void)_setStoppingFadeOutDuration:(float)arg1;
- (void)_setWantsVolumeChangesWhenPausedOrInactive:(BOOL)arg1;

// AVPlayer (AVPlayer_PIPSupport)

- (BOOL)_cachedValueForPIPModePossible;
- (BOOL)_isPIPModePossible;
- (BOOL)isPIPModePossible;

@end
