/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVPlayerItemTrackInternal : NSObject {
    AVAsset * asset;
    BOOL  enabled;
    BOOL  enabledWasSet;
    struct OpaqueFigPlaybackItem { } * figPlaybackItem;
    BOOL  figPlaybackItemIsReadyForInspection;
    NSDictionary * loudnessInfo;
    int  trackID;
    NSString * videoFieldMode;
    AVWeakReference * weakReferenceToPlayerItem;
}

@end
