/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVPlayerItemOutputInternal : NSObject {
    struct OpaqueCMTimebase { } * timebase;
    NSObject<OS_dispatch_queue> * timebaseReadWriteQueue;
    AVWeakReference * weakReference;
}

@end
