/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVRetainReleaseWeakReference : AVWeakReference {
    NSString * _cachedReferencedObjectDescription;
    id  _weakStorage;
}

- (void)dealloc;
- (id)description;
- (id)init;
- (id)initWithReferencedObject:(id)arg1;
- (id)referencedObject;

@end
