/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVURLAssetInternal : NSObject {
    NSURL * URL;
    AVAssetClientURLRequestHelper * URLRequestHelper;
    NSDictionary * initializationOptions;
    AVAssetInspectorLoader * loader;
    long  makeOneResourceLoaderOnly;
    AVAssetResourceLoader * resourceLoader;
    NSArray * tracks;
    NSObject<OS_dispatch_queue> * tracksAccessQueue;
}

@end
