/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVVideoCompositionCoreAnimationToolInternal : NSObject {
    CALayer * animationLayer;
    int  auxiliaryTrackID;
    NSArray * postProcessingVideoLayers;
    int  way;
}

@end
