/* Generated by RuntimeBrowser
   Image: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/AVFoundation.framework/AVFoundation
 */

@interface AVWeakObservationBlockFactory : NSObject

+ (id /* block */)weakObservationBlockForWeakObserver:(id)arg1 passedToBlock:(id /* block */)arg2;

@end
